// commit message FFmpeg@9340a99588 (target=1, prob=0.5702426, correct=True): Fix a possible crash on 64 bit systems when the lumSrcPtr or chrSrcPtr does not fit in 32 bits. The SWS_ACCURATE_RND is still broken though.
/*0   */ static int RENAME(swScale)(SwsContext *c, uint8_t* src[], int srcStride[], int srcSliceY,                                                                                                  // (0) 0.06836
/*2   */              int srcSliceH, uint8_t* dst[], int dstStride[]){                                                                                                                              // (1) 0.06445
/*6   */ 	/* load a few things into local vars to make the code more readable? and faster */                                                                                                        // (2) 0.03906
/*8   */ 	const int srcW= c->srcW;                                                                                                                                                                  // (24) 0.02148
/*10  */ 	const int dstW= c->dstW;                                                                                                                                                                  // (22) 0.02344
/*12  */ 	const int dstH= c->dstH;                                                                                                                                                                  // (23) 0.02344
/*14  */ 	const int chrDstW= c->chrDstW;                                                                                                                                                            // (14) 0.0332
/*16  */ 	const int chrSrcW= c->chrSrcW;                                                                                                                                                            // (16) 0.0332
/*18  */ 	const int lumXInc= c->lumXInc;                                                                                                                                                            // (20) 0.02734
/*20  */ 	const int chrXInc= c->chrXInc;                                                                                                                                                            // (19) 0.0293
/*22  */ 	const int dstFormat= c->dstFormat;                                                                                                                                                        // (21) 0.02344
/*24  */ 	const int srcFormat= c->srcFormat;                                                                                                                                                        // (25) 0.02148
/*26  */ 	const int flags= c->flags;                                                                                                                                                                // (26) 0.01758
/*28  */ 	const int canMMX2BeUsed= c->canMMX2BeUsed;                                                                                                                                                // (9) 0.03711
/*30  */ 	int16_t *vLumFilterPos= c->vLumFilterPos;                                                                                                                                                 // (5) 0.03906
/*32  */ 	int16_t *vChrFilterPos= c->vChrFilterPos;                                                                                                                                                 // (6) 0.03906
/*34  */ 	int16_t *hLumFilterPos= c->hLumFilterPos;                                                                                                                                                 // (7) 0.03906
/*36  */ 	int16_t *hChrFilterPos= c->hChrFilterPos;                                                                                                                                                 // (8) 0.03906
/*38  */ 	int16_t *vLumFilter= c->vLumFilter;                                                                                                                                                       // (12) 0.03516
/*40  */ 	int16_t *vChrFilter= c->vChrFilter;                                                                                                                                                       // (13) 0.03516
/*42  */ 	int16_t *hLumFilter= c->hLumFilter;                                                                                                                                                       // (10) 0.03516
/*44  */ 	int16_t *hChrFilter= c->hChrFilter;                                                                                                                                                       // (11) 0.03516
/*46  */ 	int32_t *lumMmxFilter= c->lumMmxFilter;                                                                                                                                                   // (4) 0.03906
/*48  */ 	int32_t *chrMmxFilter= c->chrMmxFilter;                                                                                                                                                   // (3) 0.03906
/*50  */ 	const int vLumFilterSize= c->vLumFilterSize;                                                                                                                                              // (15) 0.0332
/*52  */ 	const int vChrFilterSize= c->vChrFilterSize;                                                                                                                                              // (17) 0.0332
/*54  */ 	const int hLumFilterSize= c->hLumFilterSize;                                                                                                                                              // (18) 0.0332
/*56  */ 	const int hChrFilterSize= c->hChrFilterSize;                                                                                                                                              // 0.0
/*58  */ 	int16_t **lumPixBuf= c->lumPixBuf;                                                                                                                                                        // 0.0
/*60  */ 	int16_t **chrPixBuf= c->chrPixBuf;                                                                                                                                                        // 0.0
/*62  */ 	const int vLumBufSize= c->vLumBufSize;                                                                                                                                                    // 0.0
/*64  */ 	const int vChrBufSize= c->vChrBufSize;                                                                                                                                                    // 0.0
/*66  */ 	uint8_t *funnyYCode= c->funnyYCode;                                                                                                                                                       // 0.0
/*68  */ 	uint8_t *funnyUVCode= c->funnyUVCode;                                                                                                                                                     // 0.0
/*70  */ 	uint8_t *formatConvBuffer= c->formatConvBuffer;                                                                                                                                           // 0.0
/*72  */ 	const int chrSrcSliceY= srcSliceY >> c->chrSrcVSubSample;                                                                                                                                 // 0.0
/*74  */ 	const int chrSrcSliceH= -((-srcSliceH) >> c->chrSrcVSubSample);                                                                                                                           // 0.0
/*76  */ 	int lastDstY;                                                                                                                                                                             // 0.0
/*78  */         uint8_t *pal=NULL;                                                                                                                                                                 // 0.0
/*82  */ 	/* vars whch will change and which we need to storw back in the context */                                                                                                                // 0.0
/*84  */ 	int dstY= c->dstY;                                                                                                                                                                        // 0.0
/*86  */ 	int lumBufIndex= c->lumBufIndex;                                                                                                                                                          // 0.0
/*88  */ 	int chrBufIndex= c->chrBufIndex;                                                                                                                                                          // 0.0
/*90  */ 	int lastInLumBuf= c->lastInLumBuf;                                                                                                                                                        // 0.0
/*92  */ 	int lastInChrBuf= c->lastInChrBuf;                                                                                                                                                        // 0.0
/*94  */ 	                                                                                                                                                                                          // (27) 0.001953
/*96  */ 	if(isPacked(c->srcFormat)){                                                                                                                                                               // 0.0
/*98  */                 pal= src[1];                                                                                                                                                               // 0.0
/*100 */ 		src[0]=                                                                                                                                                                                  // 0.0
/*102 */ 		src[1]=                                                                                                                                                                                  // 0.0
/*104 */ 		src[2]= src[0];                                                                                                                                                                          // 0.0
/*106 */ 		srcStride[0]=                                                                                                                                                                            // 0.0
/*108 */ 		srcStride[1]=                                                                                                                                                                            // 0.0
/*110 */ 		srcStride[2]= srcStride[0];                                                                                                                                                              // 0.0
/*112 */ 	}                                                                                                                                                                                         // 0.0
/*114 */ 	srcStride[1]<<= c->vChrDrop;                                                                                                                                                              // 0.0
/*116 */ 	srcStride[2]<<= c->vChrDrop;                                                                                                                                                              // 0.0
/*120 */ //	printf("swscale %X %X %X -> %X %X %X\n", (int)src[0], (int)src[1], (int)src[2],                                                                                                         // 0.0
/*122 */ //		(int)dst[0], (int)dst[1], (int)dst[2]);                                                                                                                                                // 0.0
/*126 */ #if 0 //self test FIXME move to a vfilter or something                                                                                                                                     // 0.0
/*128 */ {                                                                                                                                                                                          // 0.0
/*130 */ static volatile int i=0;                                                                                                                                                                   // 0.0
/*132 */ i++;                                                                                                                                                                                       // 0.0
/*134 */ if(srcFormat==PIX_FMT_YUV420P && i==1 && srcSliceH>= c->srcH)                                                                                                                              // 0.0
/*136 */ 	selfTest(src, srcStride, c->srcW, c->srcH);                                                                                                                                               // 0.0
/*138 */ i--;                                                                                                                                                                                       // 0.0
/*140 */ }                                                                                                                                                                                          // 0.0
/*142 */ #endif                                                                                                                                                                                     // 0.0
/*146 */ //printf("sws Strides:%d %d %d -> %d %d %d\n", srcStride[0],srcStride[1],srcStride[2],                                                                                                     // 0.0
/*148 */ //dstStride[0],dstStride[1],dstStride[2]);                                                                                                                                                 // 0.0
/*152 */ 	if(dstStride[0]%8 !=0 || dstStride[1]%8 !=0 || dstStride[2]%8 !=0)                                                                                                                        // 0.0
/*154 */ 	{                                                                                                                                                                                         // 0.0
/*156 */ 		static int firstTime=1; //FIXME move this into the context perhaps                                                                                                                       // 0.0
/*158 */ 		if(flags & SWS_PRINT_INFO && firstTime)                                                                                                                                                  // 0.0
/*160 */ 		{                                                                                                                                                                                        // 0.0
/*162 */ 			av_log(c, AV_LOG_WARNING, "SwScaler: Warning: dstStride is not aligned!\n"                                                                                                              // 0.0
/*164 */ 					"SwScaler:          ->cannot do aligned memory acesses anymore\n");                                                                                                                   // 0.0
/*166 */ 			firstTime=0;                                                                                                                                                                            // 0.0
/*168 */ 		}                                                                                                                                                                                        // 0.0
/*170 */ 	}                                                                                                                                                                                         // 0.0
/*174 */ 	/* Note the user might start scaling the picture in the middle so this will not get executed                                                                                              // 0.0
/*176 */ 	   this is not really intended but works currently, so ppl might do it */                                                                                                                 // 0.0
/*178 */ 	if(srcSliceY ==0){                                                                                                                                                                        // 0.0
/*180 */ 		lumBufIndex=0;                                                                                                                                                                           // 0.0
/*182 */ 		chrBufIndex=0;                                                                                                                                                                           // 0.0
/*184 */ 		dstY=0;	                                                                                                                                                                                 // 0.0
/*186 */ 		lastInLumBuf= -1;                                                                                                                                                                        // 0.0
/*188 */ 		lastInChrBuf= -1;                                                                                                                                                                        // 0.0
/*190 */ 	}                                                                                                                                                                                         // 0.0
/*194 */ 	lastDstY= dstY;                                                                                                                                                                           // 0.0
/*198 */ 	for(;dstY < dstH; dstY++){                                                                                                                                                                // 0.0
/*200 */ 		unsigned char *dest =dst[0]+dstStride[0]*dstY;                                                                                                                                           // 0.0
/*202 */ 		const int chrDstY= dstY>>c->chrDstVSubSample;                                                                                                                                            // 0.0
/*204 */ 		unsigned char *uDest=dst[1]+dstStride[1]*chrDstY;                                                                                                                                        // 0.0
/*206 */ 		unsigned char *vDest=dst[2]+dstStride[2]*chrDstY;                                                                                                                                        // 0.0
/*210 */ 		const int firstLumSrcY= vLumFilterPos[dstY]; //First line needed as input                                                                                                                // 0.0
/*212 */ 		const int firstChrSrcY= vChrFilterPos[chrDstY]; //First line needed as input                                                                                                             // 0.0
/*214 */ 		const int lastLumSrcY= firstLumSrcY + vLumFilterSize -1; // Last line needed as input                                                                                                    // 0.0
/*216 */ 		const int lastChrSrcY= firstChrSrcY + vChrFilterSize -1; // Last line needed as input                                                                                                    // 0.0
/*220 */ //printf("dstY:%d dstH:%d firstLumSrcY:%d lastInLumBuf:%d vLumBufSize: %d vChrBufSize: %d slice: %d %d vLumFilterSize: %d firstChrSrcY: %d vChrFilterSize: %d c->chrSrcVSubSample: %d\n",  // 0.0
/*222 */ // dstY, dstH, firstLumSrcY, lastInLumBuf, vLumBufSize, vChrBufSize, srcSliceY, srcSliceH, vLumFilterSize, firstChrSrcY, vChrFilterSize,  c->chrSrcVSubSample);                            // 0.0
/*224 */ 		//handle holes (FAST_BILINEAR & weird filters)                                                                                                                                           // 0.0
/*226 */ 		if(firstLumSrcY > lastInLumBuf) lastInLumBuf= firstLumSrcY-1;                                                                                                                            // 0.0
/*228 */ 		if(firstChrSrcY > lastInChrBuf) lastInChrBuf= firstChrSrcY-1;                                                                                                                            // 0.0
/*230 */ //printf("%d %d %d\n", firstChrSrcY, lastInChrBuf, vChrBufSize);                                                                                                                           // 0.0
/*232 */ 		ASSERT(firstLumSrcY >= lastInLumBuf - vLumBufSize + 1)                                                                                                                                   // 0.0
/*234 */ 		ASSERT(firstChrSrcY >= lastInChrBuf - vChrBufSize + 1)                                                                                                                                   // 0.0
/*238 */ 		// Do we have enough lines in this slice to output the dstY line                                                                                                                         // 0.0
/*240 */ 		if(lastLumSrcY < srcSliceY + srcSliceH && lastChrSrcY < -((-srcSliceY - srcSliceH)>>c->chrSrcVSubSample))                                                                                // 0.0
/*242 */ 		{                                                                                                                                                                                        // 0.0
/*244 */ 			//Do horizontal scaling                                                                                                                                                                 // 0.0
/*246 */ 			while(lastInLumBuf < lastLumSrcY)                                                                                                                                                       // 0.0
/*248 */ 			{                                                                                                                                                                                       // 0.0
/*250 */ 				uint8_t *s= src[0]+(lastInLumBuf + 1 - srcSliceY)*srcStride[0];                                                                                                                        // 0.0
/*252 */ 				lumBufIndex++;                                                                                                                                                                         // 0.0
/*254 */ //				printf("%d %d %d %d\n", lumBufIndex, vLumBufSize, lastInLumBuf,  lastLumSrcY);                                                                                                       // 0.0
/*256 */ 				ASSERT(lumBufIndex < 2*vLumBufSize)                                                                                                                                                    // 0.0
/*258 */ 				ASSERT(lastInLumBuf + 1 - srcSliceY < srcSliceH)                                                                                                                                       // 0.0
/*260 */ 				ASSERT(lastInLumBuf + 1 - srcSliceY >= 0)                                                                                                                                              // 0.0
/*262 */ //				printf("%d %d\n", lumBufIndex, vLumBufSize);                                                                                                                                         // 0.0
/*264 */ 				RENAME(hyscale)(lumPixBuf[ lumBufIndex ], dstW, s, srcW, lumXInc,                                                                                                                      // 0.0
/*266 */ 						flags, canMMX2BeUsed, hLumFilter, hLumFilterPos, hLumFilterSize,                                                                                                                     // 0.0
/*268 */ 						funnyYCode, c->srcFormat, formatConvBuffer,                                                                                                                                          // 0.0
/*270 */ 						c->lumMmx2Filter, c->lumMmx2FilterPos, pal);                                                                                                                                         // 0.0
/*272 */ 				lastInLumBuf++;                                                                                                                                                                        // 0.0
/*274 */ 			}                                                                                                                                                                                       // 0.0
/*276 */ 			while(lastInChrBuf < lastChrSrcY)                                                                                                                                                       // 0.0
/*278 */ 			{                                                                                                                                                                                       // 0.0
/*280 */ 				uint8_t *src1= src[1]+(lastInChrBuf + 1 - chrSrcSliceY)*srcStride[1];                                                                                                                  // 0.0
/*282 */ 				uint8_t *src2= src[2]+(lastInChrBuf + 1 - chrSrcSliceY)*srcStride[2];                                                                                                                  // 0.0
/*284 */ 				chrBufIndex++;                                                                                                                                                                         // 0.0
/*286 */ 				ASSERT(chrBufIndex < 2*vChrBufSize)                                                                                                                                                    // 0.0
/*288 */ 				ASSERT(lastInChrBuf + 1 - chrSrcSliceY < (chrSrcSliceH))                                                                                                                               // 0.0
/*290 */ 				ASSERT(lastInChrBuf + 1 - chrSrcSliceY >= 0)                                                                                                                                           // 0.0
/*292 */ 				//FIXME replace parameters through context struct (some at least)                                                                                                                      // 0.0
/*296 */ 				if(!(isGray(srcFormat) || isGray(dstFormat)))                                                                                                                                          // 0.0
/*298 */ 					RENAME(hcscale)(chrPixBuf[ chrBufIndex ], chrDstW, src1, src2, chrSrcW, chrXInc,                                                                                                      // 0.0
/*300 */ 						flags, canMMX2BeUsed, hChrFilter, hChrFilterPos, hChrFilterSize,                                                                                                                     // 0.0
/*302 */ 						funnyUVCode, c->srcFormat, formatConvBuffer,                                                                                                                                         // 0.0
/*304 */ 						c->chrMmx2Filter, c->chrMmx2FilterPos, pal);                                                                                                                                         // 0.0
/*306 */ 				lastInChrBuf++;                                                                                                                                                                        // 0.0
/*308 */ 			}                                                                                                                                                                                       // 0.0
/*310 */ 			//wrap buf index around to stay inside the ring buffer                                                                                                                                  // 0.0
/*312 */ 			if(lumBufIndex >= vLumBufSize ) lumBufIndex-= vLumBufSize;                                                                                                                              // 0.0
/*314 */ 			if(chrBufIndex >= vChrBufSize ) chrBufIndex-= vChrBufSize;                                                                                                                              // 0.0
/*316 */ 		}                                                                                                                                                                                        // 0.0
/*318 */ 		else // not enough lines left in this slice -> load the rest in the buffer                                                                                                               // 0.0
/*320 */ 		{                                                                                                                                                                                        // 0.0
/*322 */ /*		printf("%d %d Last:%d %d LastInBuf:%d %d Index:%d %d Y:%d FSize: %d %d BSize: %d %d\n",                                                                                                // 0.0
/*324 */ 			firstChrSrcY,firstLumSrcY,lastChrSrcY,lastLumSrcY,                                                                                                                                      // 0.0
/*326 */ 			lastInChrBuf,lastInLumBuf,chrBufIndex,lumBufIndex,dstY,vChrFilterSize,vLumFilterSize,                                                                                                   // 0.0
/*328 */ 			vChrBufSize, vLumBufSize);*/                                                                                                                                                            // 0.0
/*332 */ 			//Do horizontal scaling                                                                                                                                                                 // 0.0
/*334 */ 			while(lastInLumBuf+1 < srcSliceY + srcSliceH)                                                                                                                                           // 0.0
/*336 */ 			{                                                                                                                                                                                       // 0.0
/*338 */ 				uint8_t *s= src[0]+(lastInLumBuf + 1 - srcSliceY)*srcStride[0];                                                                                                                        // 0.0
/*340 */ 				lumBufIndex++;                                                                                                                                                                         // 0.0
/*342 */ 				ASSERT(lumBufIndex < 2*vLumBufSize)                                                                                                                                                    // 0.0
/*344 */ 				ASSERT(lastInLumBuf + 1 - srcSliceY < srcSliceH)                                                                                                                                       // 0.0
/*346 */ 				ASSERT(lastInLumBuf + 1 - srcSliceY >= 0)                                                                                                                                              // 0.0
/*348 */ 				RENAME(hyscale)(lumPixBuf[ lumBufIndex ], dstW, s, srcW, lumXInc,                                                                                                                      // 0.0
/*350 */ 						flags, canMMX2BeUsed, hLumFilter, hLumFilterPos, hLumFilterSize,                                                                                                                     // 0.0
/*352 */ 						funnyYCode, c->srcFormat, formatConvBuffer,                                                                                                                                          // 0.0
/*354 */ 						c->lumMmx2Filter, c->lumMmx2FilterPos, pal);                                                                                                                                         // 0.0
/*356 */ 				lastInLumBuf++;                                                                                                                                                                        // 0.0
/*358 */ 			}                                                                                                                                                                                       // 0.0
/*360 */ 			while(lastInChrBuf+1 < (chrSrcSliceY + chrSrcSliceH))                                                                                                                                   // 0.0
/*362 */ 			{                                                                                                                                                                                       // 0.0
/*364 */ 				uint8_t *src1= src[1]+(lastInChrBuf + 1 - chrSrcSliceY)*srcStride[1];                                                                                                                  // 0.0
/*366 */ 				uint8_t *src2= src[2]+(lastInChrBuf + 1 - chrSrcSliceY)*srcStride[2];                                                                                                                  // 0.0
/*368 */ 				chrBufIndex++;                                                                                                                                                                         // 0.0
/*370 */ 				ASSERT(chrBufIndex < 2*vChrBufSize)                                                                                                                                                    // 0.0
/*372 */ 				ASSERT(lastInChrBuf + 1 - chrSrcSliceY < chrSrcSliceH)                                                                                                                                 // 0.0
/*374 */ 				ASSERT(lastInChrBuf + 1 - chrSrcSliceY >= 0)                                                                                                                                           // 0.0
/*378 */ 				if(!(isGray(srcFormat) || isGray(dstFormat)))                                                                                                                                          // 0.0
/*380 */ 					RENAME(hcscale)(chrPixBuf[ chrBufIndex ], chrDstW, src1, src2, chrSrcW, chrXInc,                                                                                                      // 0.0
/*382 */ 						flags, canMMX2BeUsed, hChrFilter, hChrFilterPos, hChrFilterSize,                                                                                                                     // 0.0
/*384 */ 						funnyUVCode, c->srcFormat, formatConvBuffer,                                                                                                                                         // 0.0
/*386 */ 						c->chrMmx2Filter, c->chrMmx2FilterPos, pal);                                                                                                                                         // 0.0
/*388 */ 				lastInChrBuf++;                                                                                                                                                                        // 0.0
/*390 */ 			}                                                                                                                                                                                       // 0.0
/*392 */ 			//wrap buf index around to stay inside the ring buffer                                                                                                                                  // 0.0
/*394 */ 			if(lumBufIndex >= vLumBufSize ) lumBufIndex-= vLumBufSize;                                                                                                                              // 0.0
/*396 */ 			if(chrBufIndex >= vChrBufSize ) chrBufIndex-= vChrBufSize;                                                                                                                              // 0.0
/*398 */ 			break; //we can't output a dstY line so let's try with the next slice                                                                                                                   // 0.0
/*400 */ 		}                                                                                                                                                                                        // 0.0
/*404 */ #ifdef HAVE_MMX                                                                                                                                                                            // 0.0
/*406 */ 		b5Dither= dither8[dstY&1];                                                                                                                                                               // 0.0
/*408 */ 		g6Dither= dither4[dstY&1];                                                                                                                                                               // 0.0
/*410 */ 		g5Dither= dither8[dstY&1];                                                                                                                                                               // 0.0
/*412 */ 		r5Dither= dither8[(dstY+1)&1];                                                                                                                                                           // 0.0
/*414 */ #endif                                                                                                                                                                                     // 0.0
/*416 */ 	    if(dstY < dstH-2)                                                                                                                                                                     // 0.0
/*418 */ 	    {                                                                                                                                                                                     // 0.0
/*420 */ 		int16_t **lumSrcPtr= lumPixBuf + lumBufIndex + firstLumSrcY - lastInLumBuf + vLumBufSize;                                                                                                // 0.0
/*422 */ 		int16_t **chrSrcPtr= chrPixBuf + chrBufIndex + firstChrSrcY - lastInChrBuf + vChrBufSize;                                                                                                // 0.0
/*424 */ #ifdef HAVE_MMX                                                                                                                                                                            // 0.0
/*426 */ 		int i;                                                                                                                                                                                   // 0.0
/*428 */             if(flags & SWS_ACCURATE_RND){                                                                                                                                                  // 0.0
/*430 */                         for(i=0; i<vLumFilterSize; i+=2){                                                                                                                                  // 0.0
/*432 */                                 lumMmxFilter[2*i+0]= (int32_t)lumSrcPtr[i  ];                                                                                                              // 0.0
/*434 */                                 lumMmxFilter[2*i+1]= (int32_t)lumSrcPtr[i+(vLumFilterSize>1)];                                                                                             // 0.0
/*436 */                                 lumMmxFilter[2*i+2]=                                                                                                                                       // 0.0
/*438 */                                 lumMmxFilter[2*i+3]= vLumFilter[dstY*vLumFilterSize + i    ]                                                                                               // 0.0
/*440 */                                                 + (vLumFilterSize>1 ? vLumFilter[dstY*vLumFilterSize + i + 1]<<16 : 0);                                                                    // 0.0
/*442 */                         }                                                                                                                                                                  // 0.0
/*444 */                         for(i=0; i<vChrFilterSize; i+=2){                                                                                                                                  // 0.0
/*446 */                                 chrMmxFilter[2*i+0]= (int32_t)chrSrcPtr[i  ];                                                                                                              // 0.0
/*448 */                                 chrMmxFilter[2*i+1]= (int32_t)chrSrcPtr[i+(vChrFilterSize>1)];                                                                                             // 0.0
/*450 */                                 chrMmxFilter[2*i+2]=                                                                                                                                       // 0.0
/*452 */                                 chrMmxFilter[2*i+3]= vChrFilter[chrDstY*vChrFilterSize + i    ]                                                                                            // 0.0
/*454 */                                                 + (vChrFilterSize>1 ? vChrFilter[chrDstY*vChrFilterSize + i + 1]<<16 : 0);                                                                 // 0.0
/*456 */                         }                                                                                                                                                                  // 0.0
/*458 */             }else{                                                                                                                                                                         // 0.0
/*460 */ 		for(i=0; i<vLumFilterSize; i++)                                                                                                                                                          // 0.0
/*462 */ 		{                                                                                                                                                                                        // 0.0
/*464 */ 			lumMmxFilter[4*i+0]= (int32_t)lumSrcPtr[i];                                                                                                                                             // 0.0
/*466 */ 			lumMmxFilter[4*i+1]= (uint64_t)lumSrcPtr[i] >> 32;                                                                                                                                      // 0.0
/*468 */ 			lumMmxFilter[4*i+2]=                                                                                                                                                                    // 0.0
/*470 */ 			lumMmxFilter[4*i+3]=                                                                                                                                                                    // 0.0
/*472 */ 				((uint16_t)vLumFilter[dstY*vLumFilterSize + i])*0x10001;                                                                                                                               // 0.0
/*474 */ 		}                                                                                                                                                                                        // 0.0
/*476 */ 		for(i=0; i<vChrFilterSize; i++)                                                                                                                                                          // 0.0
/*478 */ 		{                                                                                                                                                                                        // 0.0
/*480 */ 			chrMmxFilter[4*i+0]= (int32_t)chrSrcPtr[i];                                                                                                                                             // 0.0
/*483 */ 			chrMmxFilter[4*i+2]=                                                                                                                                                                    // 0.0
/*485 */ 			chrMmxFilter[4*i+3]=                                                                                                                                                                    // 0.0
/*487 */ 				((uint16_t)vChrFilter[chrDstY*vChrFilterSize + i])*0x10001;                                                                                                                            // 0.0
/*489 */ 		}                                                                                                                                                                                        // 0.0
/*491 */             }                                                                                                                                                                              // 0.0
/*493 */ #endif                                                                                                                                                                                     // 0.0
/*495 */ 		if(dstFormat == PIX_FMT_NV12 || dstFormat == PIX_FMT_NV21){                                                                                                                              // 0.0
/*497 */ 			const int chrSkipMask= (1<<c->chrDstVSubSample)-1;                                                                                                                                      // 0.0
/*499 */ 			if(dstY&chrSkipMask) uDest= NULL; //FIXME split functions in lumi / chromi                                                                                                              // 0.0
/*501 */ 			RENAME(yuv2nv12X)(c,                                                                                                                                                                    // 0.0
/*503 */ 				vLumFilter+dstY*vLumFilterSize   , lumSrcPtr, vLumFilterSize,                                                                                                                          // 0.0
/*505 */ 				vChrFilter+chrDstY*vChrFilterSize, chrSrcPtr, vChrFilterSize,                                                                                                                          // 0.0
/*507 */ 				dest, uDest, dstW, chrDstW, dstFormat);                                                                                                                                                // 0.0
/*509 */ 		}                                                                                                                                                                                        // 0.0
/*511 */ 		else if(isPlanarYUV(dstFormat) || isGray(dstFormat)) //YV12 like                                                                                                                         // 0.0
/*513 */ 		{                                                                                                                                                                                        // 0.0
/*515 */ 			const int chrSkipMask= (1<<c->chrDstVSubSample)-1;                                                                                                                                      // 0.0
/*517 */ 			if((dstY&chrSkipMask) || isGray(dstFormat)) uDest=vDest= NULL; //FIXME split functions in lumi / chromi                                                                                 // 0.0
/*519 */ 			if(vLumFilterSize == 1 && vChrFilterSize == 1) // Unscaled YV12                                                                                                                         // 0.0
/*521 */ 			{                                                                                                                                                                                       // 0.0
/*523 */ 				int16_t *lumBuf = lumPixBuf[0];                                                                                                                                                        // 0.0
/*525 */ 				int16_t *chrBuf= chrPixBuf[0];                                                                                                                                                         // 0.0
/*527 */ 				RENAME(yuv2yuv1)(lumBuf, chrBuf, dest, uDest, vDest, dstW, chrDstW);                                                                                                                   // 0.0
/*529 */ 			}                                                                                                                                                                                       // 0.0
/*531 */ 			else //General YV12                                                                                                                                                                     // 0.0
/*533 */ 			{                                                                                                                                                                                       // 0.0
/*535 */ 				RENAME(yuv2yuvX)(c,                                                                                                                                                                    // 0.0
/*537 */ 					vLumFilter+dstY*vLumFilterSize   , lumSrcPtr, vLumFilterSize,                                                                                                                         // 0.0
/*539 */ 					vChrFilter+chrDstY*vChrFilterSize, chrSrcPtr, vChrFilterSize,                                                                                                                         // 0.0
/*541 */ 					dest, uDest, vDest, dstW, chrDstW);                                                                                                                                                   // 0.0
/*543 */ 			}                                                                                                                                                                                       // 0.0
/*545 */ 		}                                                                                                                                                                                        // 0.0
/*547 */ 		else                                                                                                                                                                                     // 0.0
/*549 */ 		{                                                                                                                                                                                        // 0.0
/*551 */ 			ASSERT(lumSrcPtr + vLumFilterSize - 1 < lumPixBuf + vLumBufSize*2);                                                                                                                     // 0.0
/*553 */ 			ASSERT(chrSrcPtr + vChrFilterSize - 1 < chrPixBuf + vChrBufSize*2);                                                                                                                     // 0.0
/*555 */ 			if(vLumFilterSize == 1 && vChrFilterSize == 2) //Unscaled RGB                                                                                                                           // 0.0
/*557 */ 			{                                                                                                                                                                                       // 0.0
/*559 */ 				int chrAlpha= vChrFilter[2*dstY+1];                                                                                                                                                    // 0.0
/*561 */ 				RENAME(yuv2packed1)(c, *lumSrcPtr, *chrSrcPtr, *(chrSrcPtr+1),                                                                                                                         // 0.0
/*563 */ 						 dest, dstW, chrAlpha, dstFormat, flags, dstY);                                                                                                                                      // 0.0
/*565 */ 			}                                                                                                                                                                                       // 0.0
/*567 */ 			else if(vLumFilterSize == 2 && vChrFilterSize == 2) //BiLinear Upscale RGB                                                                                                              // 0.0
/*569 */ 			{                                                                                                                                                                                       // 0.0
/*571 */ 				int lumAlpha= vLumFilter[2*dstY+1];                                                                                                                                                    // 0.0
/*573 */ 				int chrAlpha= vChrFilter[2*dstY+1];                                                                                                                                                    // 0.0
/*575 */                                 lumMmxFilter[2]=                                                                                                                                           // 0.0
/*577 */                                 lumMmxFilter[3]= vLumFilter[2*dstY   ]*0x10001;                                                                                                            // 0.0
/*579 */                                 chrMmxFilter[2]=                                                                                                                                           // 0.0
/*581 */                                 chrMmxFilter[3]= vChrFilter[2*chrDstY]*0x10001;                                                                                                            // 0.0
/*583 */ 				RENAME(yuv2packed2)(c, *lumSrcPtr, *(lumSrcPtr+1), *chrSrcPtr, *(chrSrcPtr+1),                                                                                                         // 0.0
/*585 */ 						 dest, dstW, lumAlpha, chrAlpha, dstY);                                                                                                                                              // 0.0
/*587 */ 			}                                                                                                                                                                                       // 0.0
/*589 */ 			else //General RGB                                                                                                                                                                      // 0.0
/*591 */ 			{                                                                                                                                                                                       // 0.0
/*593 */ 				RENAME(yuv2packedX)(c,                                                                                                                                                                 // 0.0
/*595 */ 					vLumFilter+dstY*vLumFilterSize, lumSrcPtr, vLumFilterSize,                                                                                                                            // 0.0
/*597 */ 					vChrFilter+dstY*vChrFilterSize, chrSrcPtr, vChrFilterSize,                                                                                                                            // 0.0
/*599 */ 					dest, dstW, dstY);                                                                                                                                                                    // 0.0
/*601 */ 			}                                                                                                                                                                                       // 0.0
/*603 */ 		}                                                                                                                                                                                        // 0.0
/*605 */             }                                                                                                                                                                              // 0.0
/*607 */ 	    else // hmm looks like we can't use MMX here without overwriting this array's tail                                                                                                    // 0.0
/*609 */ 	    {                                                                                                                                                                                     // 0.0
/*611 */ 		int16_t **lumSrcPtr= lumPixBuf + lumBufIndex + firstLumSrcY - lastInLumBuf + vLumBufSize;                                                                                                // 0.0
/*613 */ 		int16_t **chrSrcPtr= chrPixBuf + chrBufIndex + firstChrSrcY - lastInChrBuf + vChrBufSize;                                                                                                // 0.0
/*615 */ 		if(dstFormat == PIX_FMT_NV12 || dstFormat == PIX_FMT_NV21){                                                                                                                              // 0.0
/*617 */ 			const int chrSkipMask= (1<<c->chrDstVSubSample)-1;                                                                                                                                      // 0.0
/*619 */ 			if(dstY&chrSkipMask) uDest= NULL; //FIXME split functions in lumi / chromi                                                                                                              // 0.0
/*621 */ 			yuv2nv12XinC(                                                                                                                                                                           // 0.0
/*623 */ 				vLumFilter+dstY*vLumFilterSize   , lumSrcPtr, vLumFilterSize,                                                                                                                          // 0.0
/*625 */ 				vChrFilter+chrDstY*vChrFilterSize, chrSrcPtr, vChrFilterSize,                                                                                                                          // 0.0
/*627 */ 				dest, uDest, dstW, chrDstW, dstFormat);                                                                                                                                                // 0.0
/*629 */ 		}                                                                                                                                                                                        // 0.0
/*631 */ 		else if(isPlanarYUV(dstFormat) || isGray(dstFormat)) //YV12                                                                                                                              // 0.0
/*633 */ 		{                                                                                                                                                                                        // 0.0
/*635 */ 			const int chrSkipMask= (1<<c->chrDstVSubSample)-1;                                                                                                                                      // 0.0
/*637 */ 			if((dstY&chrSkipMask) || isGray(dstFormat)) uDest=vDest= NULL; //FIXME split functions in lumi / chromi                                                                                 // 0.0
/*639 */ 			yuv2yuvXinC(                                                                                                                                                                            // 0.0
/*641 */ 				vLumFilter+dstY*vLumFilterSize   , lumSrcPtr, vLumFilterSize,                                                                                                                          // 0.0
/*643 */ 				vChrFilter+chrDstY*vChrFilterSize, chrSrcPtr, vChrFilterSize,                                                                                                                          // 0.0
/*645 */ 				dest, uDest, vDest, dstW, chrDstW);                                                                                                                                                    // 0.0
/*647 */ 		}                                                                                                                                                                                        // 0.0
/*649 */ 		else                                                                                                                                                                                     // 0.0
/*651 */ 		{                                                                                                                                                                                        // 0.0
/*653 */ 			ASSERT(lumSrcPtr + vLumFilterSize - 1 < lumPixBuf + vLumBufSize*2);                                                                                                                     // 0.0
/*655 */ 			ASSERT(chrSrcPtr + vChrFilterSize - 1 < chrPixBuf + vChrBufSize*2);                                                                                                                     // 0.0
/*657 */ 			yuv2packedXinC(c,                                                                                                                                                                       // 0.0
/*659 */ 				vLumFilter+dstY*vLumFilterSize, lumSrcPtr, vLumFilterSize,                                                                                                                             // 0.0
/*661 */ 				vChrFilter+dstY*vChrFilterSize, chrSrcPtr, vChrFilterSize,                                                                                                                             // 0.0
/*663 */ 				dest, dstW, dstY);                                                                                                                                                                     // 0.0
/*665 */ 		}                                                                                                                                                                                        // 0.0
/*667 */ 	    }                                                                                                                                                                                     // 0.0
/*669 */ 	}                                                                                                                                                                                         // 0.0
/*673 */ #ifdef HAVE_MMX                                                                                                                                                                            // 0.0
/*675 */ 	__asm __volatile(SFENCE:::"memory");                                                                                                                                                      // 0.0
/*677 */ 	__asm __volatile(EMMS:::"memory");                                                                                                                                                        // 0.0
/*679 */ #endif                                                                                                                                                                                     // 0.0
/*681 */ 	/* store changed local vars back in the context */                                                                                                                                        // 0.0
/*683 */ 	c->dstY= dstY;                                                                                                                                                                            // 0.0
/*685 */ 	c->lumBufIndex= lumBufIndex;                                                                                                                                                              // 0.0
/*687 */ 	c->chrBufIndex= chrBufIndex;                                                                                                                                                              // 0.0
/*689 */ 	c->lastInLumBuf= lastInLumBuf;                                                                                                                                                            // 0.0
/*691 */ 	c->lastInChrBuf= lastInChrBuf;                                                                                                                                                            // 0.0
/*695 */ 	return dstY - lastDstY;                                                                                                                                                                   // 0.0
/*697 */ }                                                                                                                                                                                          // 0.0
