// commit message FFmpeg@369cb092ec (target=1, prob=0.6571967, correct=True): avconv: add support for audio filters.
/*0   */ static void do_audio_out(AVFormatContext *s, OutputStream *ost,                                                                                                                                                                     // (11) 0.03711
/*2   */                          InputStream *ist, AVFrame *decoded_frame)                                                                                                                                                                  // (1) 0.07227
/*4   */ {                                                                                                                                                                                                                                   // (22) 0.001953
/*6   */     uint8_t *buftmp;                                                                                                                                                                                                                // (19) 0.02344
/*10  */     int size_out, frame_bytes, resample_changed, ret;                                                                                                                                                                               // (10) 0.03711
/*12  */     AVCodecContext *enc = ost->st->codec;                                                                                                                                                                                           // (16) 0.0332
/*14  */     AVCodecContext *dec = ist->st->codec;                                                                                                                                                                                           // (15) 0.03516
/*16  */     int osize = av_get_bytes_per_sample(enc->sample_fmt);                                                                                                                                                                           // (8) 0.04687
/*18  */     int isize = av_get_bytes_per_sample(dec->sample_fmt);                                                                                                                                                                           // (9) 0.04687
/*20  */     uint8_t *buf = decoded_frame->data[0];                                                                                                                                                                                          // (13) 0.03711
/*22  */     int size     = decoded_frame->nb_samples * dec->channels * isize;                                                                                                                                                               // (5) 0.05469
/*24  */     int out_linesize = 0;                                                                                                                                                                                                           // (20) 0.02148
/*26  */     int buf_linesize = decoded_frame->linesize[0];                                                                                                                                                                                  // (12) 0.03711
/*30  */     get_default_channel_layouts(ost, ist);                                                                                                                                                                                          // (17) 0.0332
/*34  */     if (alloc_audio_output_buf(dec, enc, decoded_frame->nb_samples, &out_linesize) < 0) {                                                                                                                                           // (0) 0.07227
/*36  */         av_log(NULL, AV_LOG_FATAL, "Error allocating audio buffer\n");                                                                                                                                                              // (3) 0.05859
/*38  */         exit_program(1);                                                                                                                                                                                                            // (18) 0.02539
/*40  */     }                                                                                                                                                                                                                               // (21) 0.007812
/*44  */     if (audio_sync_method > 1                      ||                                                                                                                                                                               // (2) 0.06641
/*46  */         enc->channels       != dec->channels       ||                                                                                                                                                                               // (4) 0.05664
/*48  */         enc->channel_layout != dec->channel_layout ||                                                                                                                                                                               // (14) 0.03711
/*50  */         enc->sample_rate    != dec->sample_rate    ||                                                                                                                                                                               // (6) 0.04883
/*52  */         dec->sample_fmt     != enc->sample_fmt)                                                                                                                                                                                     // (7) 0.04883
/*54  */         ost->audio_resample = 1;                                                                                                                                                                                                    // 0.0
/*58  */     resample_changed = ost->resample_sample_fmt  != dec->sample_fmt ||                                                                                                                                                              // 0.0
/*60  */                        ost->resample_channels    != dec->channels   ||                                                                                                                                                              // 0.0
/*62  */                        ost->resample_channel_layout != dec->channel_layout ||                                                                                                                                                       // 0.0
/*64  */                        ost->resample_sample_rate != dec->sample_rate;                                                                                                                                                               // 0.0
/*68  */     if ((ost->audio_resample && !ost->avr) || resample_changed) {                                                                                                                                                                   // 0.0
/*70  */         if (resample_changed) {                                                                                                                                                                                                     // 0.0
/*72  */             av_log(NULL, AV_LOG_INFO, "Input stream #%d:%d frame changed from rate:%d fmt:%s ch:%d chl:0x%"PRIx64" to rate:%d fmt:%s ch:%d chl:0x%"PRIx64"\n",                                                                      // 0.0
/*74  */                    ist->file_index, ist->st->index,                                                                                                                                                                                 // 0.0
/*76  */                    ost->resample_sample_rate, av_get_sample_fmt_name(ost->resample_sample_fmt),                                                                                                                                     // 0.0
/*78  */                    ost->resample_channels, ost->resample_channel_layout,                                                                                                                                                            // 0.0
/*80  */                    dec->sample_rate, av_get_sample_fmt_name(dec->sample_fmt),                                                                                                                                                       // 0.0
/*82  */                    dec->channels, dec->channel_layout);                                                                                                                                                                             // 0.0
/*84  */             ost->resample_sample_fmt  = dec->sample_fmt;                                                                                                                                                                            // 0.0
/*86  */             ost->resample_channels    = dec->channels;                                                                                                                                                                              // 0.0
/*88  */             ost->resample_channel_layout = dec->channel_layout;                                                                                                                                                                     // 0.0
/*90  */             ost->resample_sample_rate = dec->sample_rate;                                                                                                                                                                           // 0.0
/*92  */             if (ost->avr)                                                                                                                                                                                                           // 0.0
/*94  */                 avresample_close(ost->avr);                                                                                                                                                                                         // 0.0
/*96  */         }                                                                                                                                                                                                                           // 0.0
/*98  */         /* if audio_sync_method is >1 the resampler is needed for audio drift compensation */                                                                                                                                       // 0.0
/*100 */         if (audio_sync_method <= 1 &&                                                                                                                                                                                               // 0.0
/*102 */             ost->resample_sample_fmt  == enc->sample_fmt &&                                                                                                                                                                         // 0.0
/*104 */             ost->resample_channels    == enc->channels   &&                                                                                                                                                                         // 0.0
/*106 */             ost->resample_channel_layout == enc->channel_layout &&                                                                                                                                                                  // 0.0
/*108 */             ost->resample_sample_rate == enc->sample_rate) {                                                                                                                                                                        // 0.0
/*110 */             ost->audio_resample = 0;                                                                                                                                                                                                // 0.0
/*112 */         } else if (ost->audio_resample) {                                                                                                                                                                                           // 0.0
/*114 */             if (!ost->avr) {                                                                                                                                                                                                        // 0.0
/*116 */                 ost->avr = avresample_alloc_context();                                                                                                                                                                              // 0.0
/*118 */                 if (!ost->avr) {                                                                                                                                                                                                    // 0.0
/*120 */                     av_log(NULL, AV_LOG_FATAL, "Error allocating context for libavresample\n");                                                                                                                                     // 0.0
/*122 */                     exit_program(1);                                                                                                                                                                                                // 0.0
/*124 */                 }                                                                                                                                                                                                                   // 0.0
/*126 */             }                                                                                                                                                                                                                       // 0.0
/*130 */             av_opt_set_int(ost->avr, "in_channel_layout",  dec->channel_layout, 0);                                                                                                                                                 // 0.0
/*132 */             av_opt_set_int(ost->avr, "in_sample_fmt",      dec->sample_fmt,     0);                                                                                                                                                 // 0.0
/*134 */             av_opt_set_int(ost->avr, "in_sample_rate",     dec->sample_rate,    0);                                                                                                                                                 // 0.0
/*136 */             av_opt_set_int(ost->avr, "out_channel_layout", enc->channel_layout, 0);                                                                                                                                                 // 0.0
/*138 */             av_opt_set_int(ost->avr, "out_sample_fmt",     enc->sample_fmt,     0);                                                                                                                                                 // 0.0
/*140 */             av_opt_set_int(ost->avr, "out_sample_rate",    enc->sample_rate,    0);                                                                                                                                                 // 0.0
/*142 */             if (audio_sync_method > 1)                                                                                                                                                                                              // 0.0
/*144 */                 av_opt_set_int(ost->avr, "force_resampling", 1, 0);                                                                                                                                                                 // 0.0
/*148 */             /* if both the input and output formats are s16 or u8, use s16 as                                                                                                                                                       // 0.0
/*150 */                the internal sample format */                                                                                                                                                                                        // 0.0
/*152 */             if (av_get_bytes_per_sample(dec->sample_fmt) <= 2 &&                                                                                                                                                                    // 0.0
/*154 */                 av_get_bytes_per_sample(enc->sample_fmt) <= 2) {                                                                                                                                                                    // 0.0
/*156 */                 av_opt_set_int(ost->avr, "internal_sample_fmt", AV_SAMPLE_FMT_S16P, 0);                                                                                                                                             // 0.0
/*158 */             }                                                                                                                                                                                                                       // 0.0
/*162 */             ret = avresample_open(ost->avr);                                                                                                                                                                                        // 0.0
/*164 */             if (ret < 0) {                                                                                                                                                                                                          // 0.0
/*166 */                 av_log(NULL, AV_LOG_FATAL, "Error opening libavresample\n");                                                                                                                                                        // 0.0
/*168 */                 exit_program(1);                                                                                                                                                                                                    // 0.0
/*170 */             }                                                                                                                                                                                                                       // 0.0
/*172 */         }                                                                                                                                                                                                                           // 0.0
/*174 */     }                                                                                                                                                                                                                               // 0.0
/*178 */     if (audio_sync_method > 0) {                                                                                                                                                                                                    // 0.0
/*180 */         double delta = get_sync_ipts(ost, ist->last_dts) * enc->sample_rate - ost->sync_opts -                                                                                                                                      // 0.0
/*182 */                        av_fifo_size(ost->fifo) / (enc->channels * osize);                                                                                                                                                           // 0.0
/*184 */         int idelta = delta * dec->sample_rate / enc->sample_rate;                                                                                                                                                                   // 0.0
/*186 */         int byte_delta = idelta * isize * dec->channels;                                                                                                                                                                            // 0.0
/*190 */         // FIXME resample delay                                                                                                                                                                                                     // 0.0
/*192 */         if (fabs(delta) > 50) {                                                                                                                                                                                                     // 0.0
/*194 */             if (ist->is_start || fabs(delta) > audio_drift_threshold*enc->sample_rate) {                                                                                                                                            // 0.0
/*196 */                 if (byte_delta < 0) {                                                                                                                                                                                               // 0.0
/*198 */                     byte_delta = FFMAX(byte_delta, -size);                                                                                                                                                                          // 0.0
/*200 */                     size += byte_delta;                                                                                                                                                                                             // 0.0
/*202 */                     buf  -= byte_delta;                                                                                                                                                                                             // 0.0
/*204 */                     av_log(NULL, AV_LOG_VERBOSE, "discarding %d audio samples\n",                                                                                                                                                   // 0.0
/*206 */                            -byte_delta / (isize * dec->channels));                                                                                                                                                                  // 0.0
/*208 */                     if (!size)                                                                                                                                                                                                      // 0.0
/*210 */                         return;                                                                                                                                                                                                     // 0.0
/*212 */                     ist->is_start = 0;                                                                                                                                                                                              // 0.0
/*214 */                 } else {                                                                                                                                                                                                            // 0.0
/*216 */                     av_fast_malloc(&async_buf, &allocated_async_buf_size,                                                                                                                                                           // 0.0
/*218 */                                    byte_delta + size);                                                                                                                                                                              // 0.0
/*220 */                     if (!async_buf) {                                                                                                                                                                                               // 0.0
/*222 */                         av_log(NULL, AV_LOG_FATAL, "Out of memory in do_audio_out\n");                                                                                                                                              // 0.0
/*224 */                         exit_program(1);                                                                                                                                                                                            // 0.0
/*226 */                     }                                                                                                                                                                                                               // 0.0
/*230 */                     if (alloc_audio_output_buf(dec, enc, decoded_frame->nb_samples + idelta, &out_linesize) < 0) {                                                                                                                  // 0.0
/*232 */                         av_log(NULL, AV_LOG_FATAL, "Error allocating audio buffer\n");                                                                                                                                              // 0.0
/*234 */                         exit_program(1);                                                                                                                                                                                            // 0.0
/*236 */                     }                                                                                                                                                                                                               // 0.0
/*238 */                     ist->is_start = 0;                                                                                                                                                                                              // 0.0
/*242 */                     generate_silence(async_buf, dec->sample_fmt, byte_delta);                                                                                                                                                       // 0.0
/*244 */                     memcpy(async_buf + byte_delta, buf, size);                                                                                                                                                                      // 0.0
/*246 */                     buf = async_buf;                                                                                                                                                                                                // 0.0
/*248 */                     size += byte_delta;                                                                                                                                                                                             // 0.0
/*250 */                     buf_linesize = allocated_async_buf_size;                                                                                                                                                                        // 0.0
/*252 */                     av_log(NULL, AV_LOG_VERBOSE, "adding %d audio samples of silence\n", idelta);                                                                                                                                   // 0.0
/*254 */                 }                                                                                                                                                                                                                   // 0.0
/*256 */             } else if (audio_sync_method > 1) {                                                                                                                                                                                     // 0.0
/*258 */                 int comp = av_clip(delta, -audio_sync_method, audio_sync_method);                                                                                                                                                   // 0.0
/*260 */                 av_log(NULL, AV_LOG_VERBOSE, "compensating audio timestamp drift:%f compensation:%d in:%d\n",                                                                                                                       // 0.0
/*262 */                        delta, comp, enc->sample_rate);                                                                                                                                                                              // 0.0
/*264 */ //                fprintf(stderr, "drift:%f len:%d opts:%"PRId64" ipts:%"PRId64" fifo:%d\n", delta, -1, ost->sync_opts, (int64_t)(get_sync_ipts(ost) * enc->sample_rate), av_fifo_size(ost->fifo)/(ost->st->codec->channels * 2));  // 0.0
/*266 */                 avresample_set_compensation(ost->avr, comp, enc->sample_rate);                                                                                                                                                      // 0.0
/*268 */             }                                                                                                                                                                                                                       // 0.0
/*270 */         }                                                                                                                                                                                                                           // 0.0
/*272 */     } else if (audio_sync_method == 0)                                                                                                                                                                                              // 0.0
/*274 */         ost->sync_opts = lrintf(get_sync_ipts(ost, ist->last_dts) * enc->sample_rate) -                                                                                                                                             // 0.0
/*276 */                                 av_fifo_size(ost->fifo) / (enc->channels * osize); // FIXME wrong                                                                                                                                   // 0.0
/*280 */     if (ost->audio_resample) {                                                                                                                                                                                                      // 0.0
/*282 */         buftmp = audio_buf;                                                                                                                                                                                                         // 0.0
/*284 */         size_out = avresample_convert(ost->avr, (void **)&buftmp,                                                                                                                                                                   // 0.0
/*286 */                                       allocated_audio_buf_size, out_linesize,                                                                                                                                                       // 0.0
/*288 */                                       (void **)&buf, buf_linesize,                                                                                                                                                                  // 0.0
/*290 */                                       size / (dec->channels * isize));                                                                                                                                                              // 0.0
/*292 */         size_out = size_out * enc->channels * osize;                                                                                                                                                                                // 0.0
/*294 */     } else {                                                                                                                                                                                                                        // 0.0
/*296 */         buftmp = buf;                                                                                                                                                                                                               // 0.0
/*298 */         size_out = size;                                                                                                                                                                                                            // 0.0
/*300 */     }                                                                                                                                                                                                                               // 0.0
/*304 */     /* now encode as many frames as possible */                                                                                                                                                                                     // 0.0
/*306 */     if (!(enc->codec->capabilities & CODEC_CAP_VARIABLE_FRAME_SIZE)) {                                                                                                                                                              // 0.0
/*308 */         /* output resampled raw samples */                                                                                                                                                                                          // 0.0
/*310 */         if (av_fifo_realloc2(ost->fifo, av_fifo_size(ost->fifo) + size_out) < 0) {                                                                                                                                                  // 0.0
/*312 */             av_log(NULL, AV_LOG_FATAL, "av_fifo_realloc2() failed\n");                                                                                                                                                              // 0.0
/*314 */             exit_program(1);                                                                                                                                                                                                        // 0.0
/*316 */         }                                                                                                                                                                                                                           // 0.0
/*318 */         av_fifo_generic_write(ost->fifo, buftmp, size_out, NULL);                                                                                                                                                                   // 0.0
/*322 */         frame_bytes = enc->frame_size * osize * enc->channels;                                                                                                                                                                      // 0.0
/*326 */         while (av_fifo_size(ost->fifo) >= frame_bytes) {                                                                                                                                                                            // 0.0
/*328 */             av_fifo_generic_read(ost->fifo, audio_buf, frame_bytes, NULL);                                                                                                                                                          // 0.0
/*330 */             encode_audio_frame(s, ost, audio_buf, frame_bytes);                                                                                                                                                                     // 0.0
/*332 */         }                                                                                                                                                                                                                           // 0.0
/*334 */     } else {                                                                                                                                                                                                                        // 0.0
/*336 */         encode_audio_frame(s, ost, buftmp, size_out);                                                                                                                                                                               // 0.0
/*338 */     }                                                                                                                                                                                                                               // 0.0
/*340 */ }                                                                                                                                                                                                                                   // 0.0
