// commit message FFmpeg@d4f7d83866 (target=0, prob=0.33386976, correct=True): Rewrite fill_default_ref_list(), the old code was obfuscated beyond repair with hacks. new code is ~60lines old was ~200 Fixes at least: FRExt/HCHP2_HHI_A.264 one sample also get decoded much better: FRExt/FRExt1_Panasonic.avc (PSNR 11 -> 80) (no i do not know why, the old code was too a big mess to figure out  what it did)
/*0   */ static int fill_default_ref_list(H264Context *h){                                                                                                                                    // (12) 0.03125
/*2   */     MpegEncContext * const s = &h->s;                                                                                                                                                // (13) 0.03125
/*4   */     int i;                                                                                                                                                                           // (25) 0.01172
/*6   */     int smallest_poc_greater_than_current = -1;                                                                                                                                      // (8) 0.03711
/*8   */     int structure_sel;                                                                                                                                                               // (24) 0.01562
/*10  */     Picture sorted_short_ref[32];                                                                                                                                                    // (19) 0.02344
/*12  */     Picture field_entry_list[2][32];                                                                                                                                                 // (14) 0.02734
/*14  */     Picture *frame_list[2];                                                                                                                                                          // (22) 0.02148
/*18  */     if (FIELD_PICTURE) {                                                                                                                                                             // (18) 0.02344
/*20  */         structure_sel = PICT_FRAME;                                                                                                                                                  // (11) 0.0332
/*22  */         frame_list[0] = field_entry_list[0];                                                                                                                                         // (4) 0.04297
/*24  */         frame_list[1] = field_entry_list[1];                                                                                                                                         // (5) 0.04297
/*26  */     } else {                                                                                                                                                                         // (26) 0.01172
/*28  */         structure_sel = 0;                                                                                                                                                           // (17) 0.02539
/*30  */         frame_list[0] = h->default_ref_list[0];                                                                                                                                      // (2) 0.04687
/*32  */         frame_list[1] = h->default_ref_list[1];                                                                                                                                      // (3) 0.04687
/*34  */     }                                                                                                                                                                                // (27) 0.007813
/*38  */     if(h->slice_type_nos==FF_B_TYPE){                                                                                                                                                // (9) 0.03711
/*40  */         int list;                                                                                                                                                                    // (23) 0.01953
/*42  */         int len[2];                                                                                                                                                                  // (21) 0.02344
/*44  */         int short_len[2];                                                                                                                                                            // (16) 0.02734
/*46  */         int out_i;                                                                                                                                                                   // (20) 0.02344
/*48  */         int limit= INT_MIN;                                                                                                                                                          // (15) 0.02734
/*52  */         /* sort frame according to POC in B slice */                                                                                                                                 // (10) 0.03516
/*54  */         for(out_i=0; out_i<h->short_ref_count; out_i++){                                                                                                                             // (0) 0.0625
/*56  */             int best_i=INT_MIN;                                                                                                                                                      // (7) 0.03906
/*58  */             int best_poc=INT_MAX;                                                                                                                                                    // (6) 0.04102
/*62  */             for(i=0; i<h->short_ref_count; i++){                                                                                                                                     // (1) 0.05859
/*64  */                 const int poc= h->short_ref[i]->poc;                                                                                                                                 // 0.0
/*66  */                 if(poc > limit && poc < best_poc){                                                                                                                                   // 0.0
/*68  */                     best_poc= poc;                                                                                                                                                   // 0.0
/*70  */                     best_i= i;                                                                                                                                                       // 0.0
/*72  */                 }                                                                                                                                                                    // 0.0
/*74  */             }                                                                                                                                                                        // 0.0
/*78  */             assert(best_i != INT_MIN);                                                                                                                                               // 0.0
/*82  */             limit= best_poc;                                                                                                                                                         // 0.0
/*84  */             sorted_short_ref[out_i]= *h->short_ref[best_i];                                                                                                                          // 0.0
/*86  */             tprintf(h->s.avctx, "sorted poc: %d->%d poc:%d fn:%d\n", best_i, out_i, sorted_short_ref[out_i].poc, sorted_short_ref[out_i].frame_num);                                 // 0.0
/*88  */             if (-1 == smallest_poc_greater_than_current) {                                                                                                                           // 0.0
/*90  */                 if (h->short_ref[best_i]->poc >= s->current_picture_ptr->poc) {                                                                                                      // 0.0
/*92  */                     smallest_poc_greater_than_current = out_i;                                                                                                                       // 0.0
/*94  */                 }                                                                                                                                                                    // 0.0
/*96  */             }                                                                                                                                                                        // 0.0
/*98  */         }                                                                                                                                                                            // 0.0
/*102 */         tprintf(h->s.avctx, "current poc: %d, smallest_poc_greater_than_current: %d\n", s->current_picture_ptr->poc, smallest_poc_greater_than_current);                             // 0.0
/*106 */         // find the largest POC                                                                                                                                                      // 0.0
/*108 */         for(list=0; list<2; list++){                                                                                                                                                 // 0.0
/*110 */             int index = 0;                                                                                                                                                           // 0.0
/*112 */             int j= -99;                                                                                                                                                              // 0.0
/*114 */             int step= list ? -1 : 1;                                                                                                                                                 // 0.0
/*118 */             for(i=0; i<h->short_ref_count && index < h->ref_count[list]; i++, j+=step) {                                                                                             // 0.0
/*120 */                 int sel;                                                                                                                                                             // 0.0
/*122 */                 while(j<0 || j>= h->short_ref_count){                                                                                                                                // 0.0
/*124 */                     if(j != -99 && step == (list ? -1 : 1))                                                                                                                          // 0.0
/*126 */                         return -1;                                                                                                                                                   // 0.0
/*128 */                     step = -step;                                                                                                                                                    // 0.0
/*130 */                     j= smallest_poc_greater_than_current + (step>>1);                                                                                                                // 0.0
/*132 */                 }                                                                                                                                                                    // 0.0
/*134 */                 sel = sorted_short_ref[j].reference | structure_sel;                                                                                                                 // 0.0
/*136 */                 if(sel != PICT_FRAME) continue;                                                                                                                                      // 0.0
/*138 */                 frame_list[list][index  ]= sorted_short_ref[j];                                                                                                                      // 0.0
/*140 */                 frame_list[list][index++].pic_id= sorted_short_ref[j].frame_num;                                                                                                     // 0.0
/*142 */             }                                                                                                                                                                        // 0.0
/*144 */             short_len[list] = index;                                                                                                                                                 // 0.0
/*148 */             for(i = 0; i < 16 && index < h->ref_count[ list ]; i++){                                                                                                                 // 0.0
/*150 */                 int sel;                                                                                                                                                             // 0.0
/*152 */                 if(h->long_ref[i] == NULL) continue;                                                                                                                                 // 0.0
/*154 */                 sel = h->long_ref[i]->reference | structure_sel;                                                                                                                     // 0.0
/*156 */                 if(sel != PICT_FRAME) continue;                                                                                                                                      // 0.0
/*160 */                 frame_list[ list ][index  ]= *h->long_ref[i];                                                                                                                        // 0.0
/*162 */                 frame_list[ list ][index++].pic_id= i;                                                                                                                               // 0.0
/*164 */             }                                                                                                                                                                        // 0.0
/*166 */             len[list] = index;                                                                                                                                                       // 0.0
/*168 */         }                                                                                                                                                                            // 0.0
/*172 */         for(list=0; list<2; list++){                                                                                                                                                 // 0.0
/*174 */             if (FIELD_PICTURE)                                                                                                                                                       // 0.0
/*176 */                 len[list] = split_field_ref_list(h->default_ref_list[list],                                                                                                          // 0.0
/*178 */                                                  h->ref_count[list],                                                                                                                 // 0.0
/*180 */                                                  frame_list[list],                                                                                                                   // 0.0
/*182 */                                                  len[list],                                                                                                                          // 0.0
/*184 */                                                  s->picture_structure,                                                                                                               // 0.0
/*186 */                                                  short_len[list]);                                                                                                                   // 0.0
/*190 */             // swap the two first elements of L1 when L0 and L1 are identical                                                                                                        // 0.0
/*192 */             if(list && len[0] > 1 && len[0] == len[1])                                                                                                                               // 0.0
/*194 */                 for(i=0; h->default_ref_list[0][i].data[0] == h->default_ref_list[1][i].data[0]; i++)                                                                                // 0.0
/*196 */                     if(i == len[0]){                                                                                                                                                 // 0.0
/*198 */                         FFSWAP(Picture, h->default_ref_list[1][0], h->default_ref_list[1][1]);                                                                                       // 0.0
/*200 */                         break;                                                                                                                                                       // 0.0
/*202 */                     }                                                                                                                                                                // 0.0
/*206 */             if(len[list] < h->ref_count[ list ])                                                                                                                                     // 0.0
/*208 */                 memset(&h->default_ref_list[list][len[list]], 0, sizeof(Picture)*(h->ref_count[ list ] - len[list]));                                                                // 0.0
/*210 */         }                                                                                                                                                                            // 0.0
/*216 */     }else{                                                                                                                                                                           // 0.0
/*218 */         int index=0;                                                                                                                                                                 // 0.0
/*220 */         int short_len;                                                                                                                                                               // 0.0
/*222 */         for(i=0; i<h->short_ref_count; i++){                                                                                                                                         // 0.0
/*224 */             int sel;                                                                                                                                                                 // 0.0
/*226 */             sel = h->short_ref[i]->reference | structure_sel;                                                                                                                        // 0.0
/*228 */             if(sel != PICT_FRAME) continue;                                                                                                                                          // 0.0
/*230 */             frame_list[0][index  ]= *h->short_ref[i];                                                                                                                                // 0.0
/*232 */             frame_list[0][index++].pic_id= h->short_ref[i]->frame_num;                                                                                                               // 0.0
/*234 */         }                                                                                                                                                                            // 0.0
/*236 */         short_len = index;                                                                                                                                                           // 0.0
/*238 */         for(i = 0; i < 16; i++){                                                                                                                                                     // 0.0
/*240 */             int sel;                                                                                                                                                                 // 0.0
/*242 */             if(h->long_ref[i] == NULL) continue;                                                                                                                                     // 0.0
/*244 */             sel = h->long_ref[i]->reference | structure_sel;                                                                                                                         // 0.0
/*246 */             if(sel != PICT_FRAME) continue;                                                                                                                                          // 0.0
/*248 */             frame_list[0][index  ]= *h->long_ref[i];                                                                                                                                 // 0.0
/*250 */             frame_list[0][index++].pic_id= i;                                                                                                                                        // 0.0
/*252 */         }                                                                                                                                                                            // 0.0
/*256 */         if (FIELD_PICTURE)                                                                                                                                                           // 0.0
/*258 */             index = split_field_ref_list(h->default_ref_list[0],                                                                                                                     // 0.0
/*260 */                                          h->ref_count[0], frame_list[0],                                                                                                             // 0.0
/*262 */                                          index, s->picture_structure,                                                                                                                // 0.0
/*264 */                                          short_len);                                                                                                                                 // 0.0
/*268 */         if(index < h->ref_count[0])                                                                                                                                                  // 0.0
/*270 */             memset(&h->default_ref_list[0][index], 0, sizeof(Picture)*(h->ref_count[0] - index));                                                                                    // 0.0
/*272 */     }                                                                                                                                                                                // 0.0
/*274 */ #ifdef TRACE                                                                                                                                                                         // 0.0
/*276 */     for (i=0; i<h->ref_count[0]; i++) {                                                                                                                                              // 0.0
/*278 */         tprintf(h->s.avctx, "List0: %s fn:%d 0x%p\n", (h->default_ref_list[0][i].long_ref ? "LT" : "ST"), h->default_ref_list[0][i].pic_id, h->default_ref_list[0][i].data[0]);      // 0.0
/*280 */     }                                                                                                                                                                                // 0.0
/*282 */     if(h->slice_type_nos==FF_B_TYPE){                                                                                                                                                // 0.0
/*284 */         for (i=0; i<h->ref_count[1]; i++) {                                                                                                                                          // 0.0
/*286 */             tprintf(h->s.avctx, "List1: %s fn:%d 0x%p\n", (h->default_ref_list[1][i].long_ref ? "LT" : "ST"), h->default_ref_list[1][i].pic_id, h->default_ref_list[1][i].data[0]);  // 0.0
/*288 */         }                                                                                                                                                                            // 0.0
/*290 */     }                                                                                                                                                                                // 0.0
/*292 */ #endif                                                                                                                                                                               // 0.0
/*294 */     return 0;                                                                                                                                                                        // 0.0
/*296 */ }                                                                                                                                                                                    // 0.0
