// commit message FFmpeg@461cd5bfb5 (target=0, prob=0.1517311, correct=True): add vlc for cbp=0 that is valid in 422,444
/*0   */ void mpeg1_encode_mb(MpegEncContext *s,                                                                                                                                                    // (8) 0.0332
/*2   */                      DCTELEM block[6][64],                                                                                                                                                 // (4) 0.06055
/*4   */                      int motion_x, int motion_y)                                                                                                                                           // (5) 0.05859
/*6   */ {                                                                                                                                                                                          // (17) 0.001953
/*8   */     int i, cbp;                                                                                                                                                                            // (12) 0.01758
/*10  */     const int mb_x = s->mb_x;                                                                                                                                                              // (9) 0.03125
/*12  */     const int mb_y = s->mb_y;                                                                                                                                                              // (10) 0.03125
/*14  */     const int first_mb= mb_x == s->resync_mb_x && mb_y == s->resync_mb_y;                                                                                                                  // (3) 0.07227
/*18  */     /* compute cbp */                                                                                                                                                                      // (13) 0.01563
/*20  */     cbp = 0;                                                                                                                                                                               // (14) 0.01562
/*22  */     for(i=0;i<6;i++) {                                                                                                                                                                     // (11) 0.03125
/*24  */         if (s->block_last_index[i] >= 0)                                                                                                                                                   // (7) 0.04297
/*26  */             cbp |= 1 << (5 - i);                                                                                                                                                           // (6) 0.04297
/*28  */     }                                                                                                                                                                                      // (15) 0.007812
/*30  */                                                                                                                                                                                            // (16) 0.007812
/*32  */     if (cbp == 0 && !first_mb && (mb_x != s->mb_width - 1 || (mb_y != s->mb_height - 1 && s->codec_id == CODEC_ID_MPEG1VIDEO)) &&                                                          // (1) 0.1191
/*34  */         ((s->pict_type == P_TYPE && s->mv_type == MV_TYPE_16X16 && (motion_x | motion_y) == 0) ||                                                                                          // (2) 0.08984
/*36  */         (s->pict_type == B_TYPE && s->mv_dir == s->last_mv_dir && (((s->mv_dir & MV_DIR_FORWARD) ? ((s->mv[0][0][0] - s->last_mv[0][0][0])|(s->mv[0][0][1] - s->last_mv[0][0][1])) : 0) |  // (0) 0.2129
/*38  */         ((s->mv_dir & MV_DIR_BACKWARD) ? ((s->mv[1][0][0] - s->last_mv[1][0][0])|(s->mv[1][0][1] - s->last_mv[1][0][1])) : 0)) == 0))) {                                                   // 0.0
/*40  */         s->mb_skip_run++;                                                                                                                                                                  // 0.0
/*42  */         s->qscale -= s->dquant;                                                                                                                                                            // 0.0
/*44  */         s->skip_count++;                                                                                                                                                                   // 0.0
/*46  */         s->misc_bits++;                                                                                                                                                                    // 0.0
/*48  */         s->last_bits++;                                                                                                                                                                    // 0.0
/*50  */         if(s->pict_type == P_TYPE){                                                                                                                                                        // 0.0
/*52  */             s->last_mv[0][1][0]= s->last_mv[0][0][0]=                                                                                                                                      // 0.0
/*54  */             s->last_mv[0][1][1]= s->last_mv[0][0][1]= 0;                                                                                                                                   // 0.0
/*56  */         }                                                                                                                                                                                  // 0.0
/*58  */     } else {                                                                                                                                                                               // 0.0
/*60  */         if(first_mb){                                                                                                                                                                      // 0.0
/*62  */             assert(s->mb_skip_run == 0);                                                                                                                                                   // 0.0
/*64  */             encode_mb_skip_run(s, s->mb_x);                                                                                                                                                // 0.0
/*66  */         }else{                                                                                                                                                                             // 0.0
/*68  */             encode_mb_skip_run(s, s->mb_skip_run);                                                                                                                                         // 0.0
/*70  */         }                                                                                                                                                                                  // 0.0
/*72  */                                                                                                                                                                                            // 0.0
/*74  */         if (s->pict_type == I_TYPE) {                                                                                                                                                      // 0.0
/*76  */             if(s->dquant && cbp){                                                                                                                                                          // 0.0
/*78  */                 put_mb_modes(s, 2, 1, 0, 0); /* macroblock_type : macroblock_quant = 1 */                                                                                                  // 0.0
/*80  */                 put_bits(&s->pb, 5, s->qscale);                                                                                                                                            // 0.0
/*82  */             }else{                                                                                                                                                                         // 0.0
/*84  */                 put_mb_modes(s, 1, 1, 0, 0); /* macroblock_type : macroblock_quant = 0 */                                                                                                  // 0.0
/*86  */                 s->qscale -= s->dquant;                                                                                                                                                    // 0.0
/*88  */             }                                                                                                                                                                              // 0.0
/*90  */             s->misc_bits+= get_bits_diff(s);                                                                                                                                               // 0.0
/*92  */             s->i_count++;                                                                                                                                                                  // 0.0
/*94  */         } else if (s->mb_intra) {                                                                                                                                                          // 0.0
/*96  */             if(s->dquant && cbp){                                                                                                                                                          // 0.0
/*98  */                 put_mb_modes(s, 6, 0x01, 0, 0);                                                                                                                                            // 0.0
/*100 */                 put_bits(&s->pb, 5, s->qscale);                                                                                                                                            // 0.0
/*102 */             }else{                                                                                                                                                                         // 0.0
/*104 */                 put_mb_modes(s, 5, 0x03, 0, 0);                                                                                                                                            // 0.0
/*106 */                 s->qscale -= s->dquant;                                                                                                                                                    // 0.0
/*108 */             }                                                                                                                                                                              // 0.0
/*110 */             s->misc_bits+= get_bits_diff(s);                                                                                                                                               // 0.0
/*112 */             s->i_count++;                                                                                                                                                                  // 0.0
/*114 */             memset(s->last_mv, 0, sizeof(s->last_mv));                                                                                                                                     // 0.0
/*116 */         } else if (s->pict_type == P_TYPE) {                                                                                                                                               // 0.0
/*118 */             if(s->mv_type == MV_TYPE_16X16){                                                                                                                                               // 0.0
/*120 */                 if (cbp != 0) {                                                                                                                                                            // 0.0
/*122 */                     if ((motion_x|motion_y) == 0) {                                                                                                                                        // 0.0
/*124 */                         if(s->dquant){                                                                                                                                                     // 0.0
/*126 */                             put_mb_modes(s, 5, 1, 0, 0); /* macroblock_pattern & quant */                                                                                                  // 0.0
/*128 */                             put_bits(&s->pb, 5, s->qscale);                                                                                                                                // 0.0
/*130 */                         }else{                                                                                                                                                             // 0.0
/*132 */                             put_mb_modes(s, 2, 1, 0, 0); /* macroblock_pattern only */                                                                                                     // 0.0
/*134 */                         }                                                                                                                                                                  // 0.0
/*136 */                         s->misc_bits+= get_bits_diff(s);                                                                                                                                   // 0.0
/*138 */                     } else {                                                                                                                                                               // 0.0
/*140 */                         if(s->dquant){                                                                                                                                                     // 0.0
/*142 */                             put_mb_modes(s, 5, 2, 1, 0); /* motion + cbp */                                                                                                                // 0.0
/*144 */                             put_bits(&s->pb, 5, s->qscale);                                                                                                                                // 0.0
/*146 */                         }else{                                                                                                                                                             // 0.0
/*148 */                             put_mb_modes(s, 1, 1, 1, 0); /* motion + cbp */                                                                                                                // 0.0
/*150 */                         }                                                                                                                                                                  // 0.0
/*152 */                         s->misc_bits+= get_bits_diff(s);                                                                                                                                   // 0.0
/*154 */                         mpeg1_encode_motion(s, motion_x - s->last_mv[0][0][0], s->f_code);    // RAL: f_code parameter added                                                               // 0.0
/*156 */                         mpeg1_encode_motion(s, motion_y - s->last_mv[0][0][1], s->f_code);    // RAL: f_code parameter added                                                               // 0.0
/*158 */                         s->mv_bits+= get_bits_diff(s);                                                                                                                                     // 0.0
/*160 */                     }                                                                                                                                                                      // 0.0
/*162 */                 } else {                                                                                                                                                                   // 0.0
/*164 */                     put_bits(&s->pb, 3, 1); /* motion only */                                                                                                                              // 0.0
/*166 */                     if (!s->frame_pred_frame_dct)                                                                                                                                          // 0.0
/*168 */                         put_bits(&s->pb, 2, 2); /* motion_type: frame */                                                                                                                   // 0.0
/*170 */                     s->misc_bits+= get_bits_diff(s);                                                                                                                                       // 0.0
/*172 */                     mpeg1_encode_motion(s, motion_x - s->last_mv[0][0][0], s->f_code);    // RAL: f_code parameter added                                                                   // 0.0
/*174 */                     mpeg1_encode_motion(s, motion_y - s->last_mv[0][0][1], s->f_code);    // RAL: f_code parameter added                                                                   // 0.0
/*176 */                     s->qscale -= s->dquant;                                                                                                                                                // 0.0
/*178 */                     s->mv_bits+= get_bits_diff(s);                                                                                                                                         // 0.0
/*180 */                 }                                                                                                                                                                          // 0.0
/*182 */                 s->last_mv[0][1][0]= s->last_mv[0][0][0]= motion_x;                                                                                                                        // 0.0
/*184 */                 s->last_mv[0][1][1]= s->last_mv[0][0][1]= motion_y;                                                                                                                        // 0.0
/*186 */             }else{                                                                                                                                                                         // 0.0
/*188 */                 assert(!s->frame_pred_frame_dct && s->mv_type == MV_TYPE_FIELD);                                                                                                           // 0.0
/*192 */                 if (cbp) {                                                                                                                                                                 // 0.0
/*194 */                     if(s->dquant){                                                                                                                                                         // 0.0
/*196 */                         put_mb_modes(s, 5, 2, 1, 1); /* motion + cbp */                                                                                                                    // 0.0
/*198 */                         put_bits(&s->pb, 5, s->qscale);                                                                                                                                    // 0.0
/*200 */                     }else{                                                                                                                                                                 // 0.0
/*202 */                         put_mb_modes(s, 1, 1, 1, 1); /* motion + cbp */                                                                                                                    // 0.0
/*204 */                     }                                                                                                                                                                      // 0.0
/*206 */                 } else {                                                                                                                                                                   // 0.0
/*208 */                     put_bits(&s->pb, 3, 1); /* motion only */                                                                                                                              // 0.0
/*210 */                     put_bits(&s->pb, 2, 1); /* motion_type: field */                                                                                                                       // 0.0
/*212 */                     s->qscale -= s->dquant;                                                                                                                                                // 0.0
/*214 */                 }                                                                                                                                                                          // 0.0
/*216 */                 s->misc_bits+= get_bits_diff(s);                                                                                                                                           // 0.0
/*218 */                 for(i=0; i<2; i++){                                                                                                                                                        // 0.0
/*220 */                     put_bits(&s->pb, 1, s->field_select[0][i]);                                                                                                                            // 0.0
/*222 */                     mpeg1_encode_motion(s, s->mv[0][i][0] -  s->last_mv[0][i][0]    , s->f_code);                                                                                          // 0.0
/*224 */                     mpeg1_encode_motion(s, s->mv[0][i][1] - (s->last_mv[0][i][1]>>1), s->f_code);                                                                                          // 0.0
/*226 */                     s->last_mv[0][i][0]=   s->mv[0][i][0];                                                                                                                                 // 0.0
/*228 */                     s->last_mv[0][i][1]= 2*s->mv[0][i][1];                                                                                                                                 // 0.0
/*230 */                 }                                                                                                                                                                          // 0.0
/*232 */                 s->mv_bits+= get_bits_diff(s);                                                                                                                                             // 0.0
/*234 */             }                                                                                                                                                                              // 0.0
/*236 */             if(cbp)                                                                                                                                                                        // 0.0
/*238 */                 put_bits(&s->pb, mbPatTable[cbp - 1][1], mbPatTable[cbp - 1][0]);                                                                                                          // 0.0
/*240 */             s->f_count++;                                                                                                                                                                  // 0.0
/*242 */         } else{                                                                                                                                                                            // 0.0
/*244 */             static const int mb_type_len[4]={0,3,4,2}; //bak,for,bi                                                                                                                        // 0.0
/*248 */             if(s->mv_type == MV_TYPE_16X16){                                                                                                                                               // 0.0
/*250 */                 if (cbp){    // With coded bloc pattern                                                                                                                                    // 0.0
/*252 */                     if (s->dquant) {                                                                                                                                                       // 0.0
/*254 */                         if(s->mv_dir == MV_DIR_FORWARD)                                                                                                                                    // 0.0
/*256 */                             put_mb_modes(s, 6, 3, 1, 0);                                                                                                                                   // 0.0
/*258 */                         else                                                                                                                                                               // 0.0
/*260 */                             put_mb_modes(s, mb_type_len[s->mv_dir]+3, 2, 1, 0);                                                                                                            // 0.0
/*262 */                         put_bits(&s->pb, 5, s->qscale);                                                                                                                                    // 0.0
/*264 */                     } else {                                                                                                                                                               // 0.0
/*266 */                         put_mb_modes(s, mb_type_len[s->mv_dir], 3, 1, 0);                                                                                                                  // 0.0
/*268 */                     }                                                                                                                                                                      // 0.0
/*270 */                 }else{    // No coded bloc pattern                                                                                                                                         // 0.0
/*272 */                     put_bits(&s->pb, mb_type_len[s->mv_dir], 2);                                                                                                                           // 0.0
/*274 */                     if (!s->frame_pred_frame_dct)                                                                                                                                          // 0.0
/*276 */                         put_bits(&s->pb, 2, 2); /* motion_type: frame */                                                                                                                   // 0.0
/*278 */                     s->qscale -= s->dquant;                                                                                                                                                // 0.0
/*280 */                 }                                                                                                                                                                          // 0.0
/*282 */                 s->misc_bits += get_bits_diff(s);                                                                                                                                          // 0.0
/*284 */                 if (s->mv_dir&MV_DIR_FORWARD){                                                                                                                                             // 0.0
/*286 */                     mpeg1_encode_motion(s, s->mv[0][0][0] - s->last_mv[0][0][0], s->f_code);                                                                                               // 0.0
/*288 */                     mpeg1_encode_motion(s, s->mv[0][0][1] - s->last_mv[0][0][1], s->f_code);                                                                                               // 0.0
/*290 */                     s->last_mv[0][0][0]=s->last_mv[0][1][0]= s->mv[0][0][0];                                                                                                               // 0.0
/*292 */                     s->last_mv[0][0][1]=s->last_mv[0][1][1]= s->mv[0][0][1];                                                                                                               // 0.0
/*294 */                     s->f_count++;                                                                                                                                                          // 0.0
/*296 */                 }                                                                                                                                                                          // 0.0
/*298 */                 if (s->mv_dir&MV_DIR_BACKWARD){                                                                                                                                            // 0.0
/*300 */                     mpeg1_encode_motion(s, s->mv[1][0][0] - s->last_mv[1][0][0], s->b_code);                                                                                               // 0.0
/*302 */                     mpeg1_encode_motion(s, s->mv[1][0][1] - s->last_mv[1][0][1], s->b_code);                                                                                               // 0.0
/*304 */                     s->last_mv[1][0][0]=s->last_mv[1][1][0]= s->mv[1][0][0];                                                                                                               // 0.0
/*306 */                     s->last_mv[1][0][1]=s->last_mv[1][1][1]= s->mv[1][0][1];                                                                                                               // 0.0
/*308 */                     s->b_count++;                                                                                                                                                          // 0.0
/*310 */                 }                                                                                                                                                                          // 0.0
/*312 */             }else{                                                                                                                                                                         // 0.0
/*314 */                 assert(s->mv_type == MV_TYPE_FIELD);                                                                                                                                       // 0.0
/*316 */                 assert(!s->frame_pred_frame_dct);                                                                                                                                          // 0.0
/*318 */                 if (cbp){    // With coded bloc pattern                                                                                                                                    // 0.0
/*320 */                     if (s->dquant) {                                                                                                                                                       // 0.0
/*322 */                         if(s->mv_dir == MV_DIR_FORWARD)                                                                                                                                    // 0.0
/*324 */                             put_mb_modes(s, 6, 3, 1, 1);                                                                                                                                   // 0.0
/*326 */                         else                                                                                                                                                               // 0.0
/*328 */                             put_mb_modes(s, mb_type_len[s->mv_dir]+3, 2, 1, 1);                                                                                                            // 0.0
/*330 */                         put_bits(&s->pb, 5, s->qscale);                                                                                                                                    // 0.0
/*332 */                     } else {                                                                                                                                                               // 0.0
/*334 */                         put_mb_modes(s, mb_type_len[s->mv_dir], 3, 1, 1);                                                                                                                  // 0.0
/*336 */                     }                                                                                                                                                                      // 0.0
/*338 */                 }else{    // No coded bloc pattern                                                                                                                                         // 0.0
/*340 */                     put_bits(&s->pb, mb_type_len[s->mv_dir], 2);                                                                                                                           // 0.0
/*342 */                     put_bits(&s->pb, 2, 1); /* motion_type: field */                                                                                                                       // 0.0
/*344 */                     s->qscale -= s->dquant;                                                                                                                                                // 0.0
/*346 */                 }                                                                                                                                                                          // 0.0
/*348 */                 s->misc_bits += get_bits_diff(s);                                                                                                                                          // 0.0
/*350 */                 if (s->mv_dir&MV_DIR_FORWARD){                                                                                                                                             // 0.0
/*352 */                     for(i=0; i<2; i++){                                                                                                                                                    // 0.0
/*354 */                         put_bits(&s->pb, 1, s->field_select[0][i]);                                                                                                                        // 0.0
/*356 */                         mpeg1_encode_motion(s, s->mv[0][i][0] -  s->last_mv[0][i][0]    , s->f_code);                                                                                      // 0.0
/*358 */                         mpeg1_encode_motion(s, s->mv[0][i][1] - (s->last_mv[0][i][1]>>1), s->f_code);                                                                                      // 0.0
/*360 */                         s->last_mv[0][i][0]=   s->mv[0][i][0];                                                                                                                             // 0.0
/*362 */                         s->last_mv[0][i][1]= 2*s->mv[0][i][1];                                                                                                                             // 0.0
/*364 */                     }                                                                                                                                                                      // 0.0
/*366 */                     s->f_count++;                                                                                                                                                          // 0.0
/*368 */                 }                                                                                                                                                                          // 0.0
/*370 */                 if (s->mv_dir&MV_DIR_BACKWARD){                                                                                                                                            // 0.0
/*372 */                     for(i=0; i<2; i++){                                                                                                                                                    // 0.0
/*374 */                         put_bits(&s->pb, 1, s->field_select[1][i]);                                                                                                                        // 0.0
/*376 */                         mpeg1_encode_motion(s, s->mv[1][i][0] -  s->last_mv[1][i][0]    , s->b_code);                                                                                      // 0.0
/*378 */                         mpeg1_encode_motion(s, s->mv[1][i][1] - (s->last_mv[1][i][1]>>1), s->b_code);                                                                                      // 0.0
/*380 */                         s->last_mv[1][i][0]=   s->mv[1][i][0];                                                                                                                             // 0.0
/*382 */                         s->last_mv[1][i][1]= 2*s->mv[1][i][1];                                                                                                                             // 0.0
/*384 */                     }                                                                                                                                                                      // 0.0
/*386 */                     s->b_count++;                                                                                                                                                          // 0.0
/*388 */                 }                                                                                                                                                                          // 0.0
/*390 */             }                                                                                                                                                                              // 0.0
/*392 */             s->mv_bits += get_bits_diff(s);                                                                                                                                                // 0.0
/*394 */             if(cbp)                                                                                                                                                                        // 0.0
/*396 */                 put_bits(&s->pb, mbPatTable[cbp - 1][1], mbPatTable[cbp - 1][0]);                                                                                                          // 0.0
/*398 */         }                                                                                                                                                                                  // 0.0
/*400 */         for(i=0;i<6;i++) {                                                                                                                                                                 // 0.0
/*402 */             if (cbp & (1 << (5 - i))) {                                                                                                                                                    // 0.0
/*404 */                 mpeg1_encode_block(s, block[i], i);                                                                                                                                        // 0.0
/*406 */             }                                                                                                                                                                              // 0.0
/*408 */         }                                                                                                                                                                                  // 0.0
/*410 */         s->mb_skip_run = 0;                                                                                                                                                                // 0.0
/*412 */         if(s->mb_intra)                                                                                                                                                                    // 0.0
/*414 */             s->i_tex_bits+= get_bits_diff(s);                                                                                                                                              // 0.0
/*416 */         else                                                                                                                                                                               // 0.0
/*418 */             s->p_tex_bits+= get_bits_diff(s);                                                                                                                                              // 0.0
/*420 */     }                                                                                                                                                                                      // 0.0
/*422 */ }                                                                                                                                                                                          // 0.0
