// commit message FFmpeg@570a4a0189 (target=0, prob=0.73479944, correct=False): avidec: use sensible error codes instead of -1
/*0  */ static int get_riff(AVFormatContext *s, AVIOContext *pb)                                      // (5) 0.0623
/*2  */ {                                                                                             // (17) 0.003279
/*4  */     AVIContext *avi = s->priv_data;                                                           // (6) 0.05246
/*6  */     char header[8];                                                                           // (14) 0.02623
/*8  */     int i;                                                                                    // (15) 0.01967
/*12 */     /* check RIFF header */                                                                   // (13) 0.02951
/*14 */     avio_read(pb, header, 4);                                                                 // (8) 0.0459
/*16 */     avi->riff_end = avio_rl32(pb);  /* RIFF chunk size */                                     // (1) 0.08525
/*18 */     avi->riff_end += avio_tell(pb); /* RIFF chunk end */                                      // (2) 0.07869
/*20 */     avio_read(pb, header+4, 4);                                                               // (7) 0.05246
/*24 */     for(i=0; avi_headers[i][0]; i++)                                                          // (4) 0.06557
/*26 */         if(!memcmp(header, avi_headers[i], 8))                                                // (3) 0.07869
/*28 */             break;                                                                            // (11) 0.04262
/*30 */     if(!avi_headers[i][0])                                                                    // (9) 0.0459
/*32 */         return -1;                                                                            // (12) 0.03607
/*36 */     if(header[7] == 0x19)                                                                     // (10) 0.0459
/*38 */         av_log(s, AV_LOG_INFO, "This file has been generated by a totally broken muxer.\n");  // (0) 0.118
/*42 */     return 0;                                                                                 // (16) 0.01967
/*44 */ }                                                                                             // (18) 0.003279
