// commit message FFmpeg@c2c1726847 (target=0, prob=0.5762653, correct=False): ffserver remove CONFIG_NOCUTILS check
/*0   */ static void compute_status(HTTPContext *c)                                                                                                                                                                                                                      // (15) 0.02148
/*2   */ {                                                                                                                                                                                                                                                               // (25) 0.001953
/*4   */     HTTPContext *c1;                                                                                                                                                                                                                                            // (16) 0.01758
/*6   */     FFStream *stream;                                                                                                                                                                                                                                           // (20) 0.01563
/*8   */     char *p;                                                                                                                                                                                                                                                    // (22) 0.01367
/*10  */     time_t ti;                                                                                                                                                                                                                                                  // (19) 0.01563
/*12  */     int i, len;                                                                                                                                                                                                                                                 // (21) 0.01562
/*14  */     AVIOContext *pb;                                                                                                                                                                                                                                            // (17) 0.01758
/*18  */     if (avio_open_dyn_buf(&pb) < 0) {                                                                                                                                                                                                                           // (8) 0.04102
/*20  */         /* XXX: return an error ? */                                                                                                                                                                                                                            // (13) 0.0293
/*22  */         c->buffer_ptr = c->buffer;                                                                                                                                                                                                                              // (10) 0.0332
/*24  */         c->buffer_end = c->buffer;                                                                                                                                                                                                                              // (11) 0.0332
/*26  */         return;                                                                                                                                                                                                                                                 // (18) 0.01758
/*28  */     }                                                                                                                                                                                                                                                           // (24) 0.007812
/*32  */     avio_printf(pb, "HTTP/1.0 200 OK\r\n");                                                                                                                                                                                                                     // (6) 0.04492
/*34  */     avio_printf(pb, "Content-type: %s\r\n", "text/html");                                                                                                                                                                                                       // (3) 0.05273
/*36  */     avio_printf(pb, "Pragma: no-cache\r\n");                                                                                                                                                                                                                    // (7) 0.04492
/*38  */     avio_printf(pb, "\r\n");                                                                                                                                                                                                                                    // (14) 0.0293
/*42  */     avio_printf(pb, "<html><head><title>%s Status</title>\n", program_name);                                                                                                                                                                                    // (1) 0.05859
/*44  */     if (c->stream->feed_filename[0])                                                                                                                                                                                                                            // (12) 0.0293
/*46  */         avio_printf(pb, "<link rel=\"shortcut icon\" href=\"%s\">\n", c->stream->feed_filename);                                                                                                                                                                // (0) 0.07422
/*48  */     avio_printf(pb, "</head>\n<body>");                                                                                                                                                                                                                         // (9) 0.03906
/*50  */     avio_printf(pb, "<h1>%s Status</h1>\n", program_name);                                                                                                                                                                                                      // (2) 0.05469
/*52  */     /* format status */                                                                                                                                                                                                                                         // (23) 0.01367
/*54  */     avio_printf(pb, "<h2>Available Streams</h2>\n");                                                                                                                                                                                                            // (5) 0.04687
/*56  */     avio_printf(pb, "<table cellspacing=0 cellpadding=4>\n");                                                                                                                                                                                                   // (4) 0.04883
/*58  */     avio_printf(pb, "<tr><th valign=top>Path<th align=left>Served<br>Conns<th><br>bytes<th valign=top>Format<th>Bit rate<br>kbits/s<th align=left>Video<br>kbits/s<th><br>Codec<th align=left>Audio<br>kbits/s<th><br>Codec<th align=left valign=top>Feed\n");  // 0.0
/*60  */     stream = first_stream;                                                                                                                                                                                                                                      // 0.0
/*62  */     while (stream != NULL) {                                                                                                                                                                                                                                    // 0.0
/*64  */         char sfilename[1024];                                                                                                                                                                                                                                   // 0.0
/*66  */         char *eosf;                                                                                                                                                                                                                                             // 0.0
/*70  */         if (stream->feed != stream) {                                                                                                                                                                                                                           // 0.0
/*72  */             av_strlcpy(sfilename, stream->filename, sizeof(sfilename) - 10);                                                                                                                                                                                    // 0.0
/*74  */             eosf = sfilename + strlen(sfilename);                                                                                                                                                                                                               // 0.0
/*76  */             if (eosf - sfilename >= 4) {                                                                                                                                                                                                                        // 0.0
/*78  */                 if (strcmp(eosf - 4, ".asf") == 0)                                                                                                                                                                                                              // 0.0
/*80  */                     strcpy(eosf - 4, ".asx");                                                                                                                                                                                                                   // 0.0
/*82  */                 else if (strcmp(eosf - 3, ".rm") == 0)                                                                                                                                                                                                          // 0.0
/*84  */                     strcpy(eosf - 3, ".ram");                                                                                                                                                                                                                   // 0.0
/*86  */                 else if (stream->fmt && !strcmp(stream->fmt->name, "rtp")) {                                                                                                                                                                                    // 0.0
/*88  */                     /* generate a sample RTSP director if                                                                                                                                                                                                       // 0.0
/*90  */                        unicast. Generate an SDP redirector if                                                                                                                                                                                                   // 0.0
/*92  */                        multicast */                                                                                                                                                                                                                             // 0.0
/*94  */                     eosf = strrchr(sfilename, '.');                                                                                                                                                                                                             // 0.0
/*96  */                     if (!eosf)                                                                                                                                                                                                                                  // 0.0
/*98  */                         eosf = sfilename + strlen(sfilename);                                                                                                                                                                                                   // 0.0
/*100 */                     if (stream->is_multicast)                                                                                                                                                                                                                   // 0.0
/*102 */                         strcpy(eosf, ".sdp");                                                                                                                                                                                                                   // 0.0
/*104 */                     else                                                                                                                                                                                                                                        // 0.0
/*106 */                         strcpy(eosf, ".rtsp");                                                                                                                                                                                                                  // 0.0
/*108 */                 }                                                                                                                                                                                                                                               // 0.0
/*110 */             }                                                                                                                                                                                                                                                   // 0.0
/*114 */             avio_printf(pb, "<tr><td><a href=\"/%s\">%s</a> ",                                                                                                                                                                                                  // 0.0
/*116 */                          sfilename, stream->filename);                                                                                                                                                                                                          // 0.0
/*118 */             avio_printf(pb, "<td align=right> %d <td align=right> ",                                                                                                                                                                                            // 0.0
/*120 */                         stream->conns_served);                                                                                                                                                                                                                  // 0.0
/*122 */             fmt_bytecount(pb, stream->bytes_served);                                                                                                                                                                                                            // 0.0
/*124 */             switch(stream->stream_type) {                                                                                                                                                                                                                       // 0.0
/*126 */             case STREAM_TYPE_LIVE: {                                                                                                                                                                                                                            // 0.0
/*128 */                     int audio_bit_rate = 0;                                                                                                                                                                                                                     // 0.0
/*130 */                     int video_bit_rate = 0;                                                                                                                                                                                                                     // 0.0
/*132 */                     const char *audio_codec_name = "";                                                                                                                                                                                                          // 0.0
/*134 */                     const char *video_codec_name = "";                                                                                                                                                                                                          // 0.0
/*136 */                     const char *audio_codec_name_extra = "";                                                                                                                                                                                                    // 0.0
/*138 */                     const char *video_codec_name_extra = "";                                                                                                                                                                                                    // 0.0
/*142 */                     for(i=0;i<stream->nb_streams;i++) {                                                                                                                                                                                                         // 0.0
/*144 */                         AVStream *st = stream->streams[i];                                                                                                                                                                                                      // 0.0
/*146 */                         AVCodec *codec = avcodec_find_encoder(st->codec->codec_id);                                                                                                                                                                             // 0.0
/*148 */                         switch(st->codec->codec_type) {                                                                                                                                                                                                         // 0.0
/*150 */                         case AVMEDIA_TYPE_AUDIO:                                                                                                                                                                                                                // 0.0
/*152 */                             audio_bit_rate += st->codec->bit_rate;                                                                                                                                                                                              // 0.0
/*154 */                             if (codec) {                                                                                                                                                                                                                        // 0.0
/*156 */                                 if (*audio_codec_name)                                                                                                                                                                                                          // 0.0
/*158 */                                     audio_codec_name_extra = "...";                                                                                                                                                                                             // 0.0
/*160 */                                 audio_codec_name = codec->name;                                                                                                                                                                                                 // 0.0
/*162 */                             }                                                                                                                                                                                                                                   // 0.0
/*164 */                             break;                                                                                                                                                                                                                              // 0.0
/*166 */                         case AVMEDIA_TYPE_VIDEO:                                                                                                                                                                                                                // 0.0
/*168 */                             video_bit_rate += st->codec->bit_rate;                                                                                                                                                                                              // 0.0
/*170 */                             if (codec) {                                                                                                                                                                                                                        // 0.0
/*172 */                                 if (*video_codec_name)                                                                                                                                                                                                          // 0.0
/*174 */                                     video_codec_name_extra = "...";                                                                                                                                                                                             // 0.0
/*176 */                                 video_codec_name = codec->name;                                                                                                                                                                                                 // 0.0
/*178 */                             }                                                                                                                                                                                                                                   // 0.0
/*180 */                             break;                                                                                                                                                                                                                              // 0.0
/*182 */                         case AVMEDIA_TYPE_DATA:                                                                                                                                                                                                                 // 0.0
/*184 */                             video_bit_rate += st->codec->bit_rate;                                                                                                                                                                                              // 0.0
/*186 */                             break;                                                                                                                                                                                                                              // 0.0
/*188 */                         default:                                                                                                                                                                                                                                // 0.0
/*190 */                             abort();                                                                                                                                                                                                                            // 0.0
/*192 */                         }                                                                                                                                                                                                                                       // 0.0
/*194 */                     }                                                                                                                                                                                                                                           // 0.0
/*196 */                     avio_printf(pb, "<td align=center> %s <td align=right> %d <td align=right> %d <td> %s %s <td align=right> %d <td> %s %s",                                                                                                                   // 0.0
/*198 */                                  stream->fmt->name,                                                                                                                                                                                                             // 0.0
/*200 */                                  stream->bandwidth,                                                                                                                                                                                                             // 0.0
/*202 */                                  video_bit_rate / 1000, video_codec_name, video_codec_name_extra,                                                                                                                                                               // 0.0
/*204 */                                  audio_bit_rate / 1000, audio_codec_name, audio_codec_name_extra);                                                                                                                                                              // 0.0
/*206 */                     if (stream->feed)                                                                                                                                                                                                                           // 0.0
/*208 */                         avio_printf(pb, "<td>%s", stream->feed->filename);                                                                                                                                                                                      // 0.0
/*210 */                     else                                                                                                                                                                                                                                        // 0.0
/*212 */                         avio_printf(pb, "<td>%s", stream->feed_filename);                                                                                                                                                                                       // 0.0
/*214 */                     avio_printf(pb, "\n");                                                                                                                                                                                                                      // 0.0
/*216 */                 }                                                                                                                                                                                                                                               // 0.0
/*218 */                 break;                                                                                                                                                                                                                                          // 0.0
/*220 */             default:                                                                                                                                                                                                                                            // 0.0
/*222 */                 avio_printf(pb, "<td align=center> - <td align=right> - <td align=right> - <td><td align=right> - <td>\n");                                                                                                                                     // 0.0
/*224 */                 break;                                                                                                                                                                                                                                          // 0.0
/*226 */             }                                                                                                                                                                                                                                                   // 0.0
/*228 */         }                                                                                                                                                                                                                                                       // 0.0
/*230 */         stream = stream->next;                                                                                                                                                                                                                                  // 0.0
/*232 */     }                                                                                                                                                                                                                                                           // 0.0
/*234 */     avio_printf(pb, "</table>\n");                                                                                                                                                                                                                              // 0.0
/*238 */     stream = first_stream;                                                                                                                                                                                                                                      // 0.0
/*240 */     while (stream != NULL) {                                                                                                                                                                                                                                    // 0.0
/*242 */         if (stream->feed == stream) {                                                                                                                                                                                                                           // 0.0
/*244 */             avio_printf(pb, "<h2>Feed %s</h2>", stream->filename);                                                                                                                                                                                              // 0.0
/*246 */             if (stream->pid) {                                                                                                                                                                                                                                  // 0.0
/*248 */                 avio_printf(pb, "Running as pid %d.\n", stream->pid);                                                                                                                                                                                           // 0.0
/*252 */ #if defined(linux) && !defined(CONFIG_NOCUTILS)                                                                                                                                                                                                                 // 0.0
/*254 */                 {                                                                                                                                                                                                                                               // 0.0
/*256 */                     FILE *pid_stat;                                                                                                                                                                                                                             // 0.0
/*258 */                     char ps_cmd[64];                                                                                                                                                                                                                            // 0.0
/*262 */                     /* This is somewhat linux specific I guess */                                                                                                                                                                                               // 0.0
/*264 */                     snprintf(ps_cmd, sizeof(ps_cmd),                                                                                                                                                                                                            // 0.0
/*266 */                              "ps -o \"%%cpu,cputime\" --no-headers %d",                                                                                                                                                                                         // 0.0
/*268 */                              stream->pid);                                                                                                                                                                                                                      // 0.0
/*272 */                     pid_stat = popen(ps_cmd, "r");                                                                                                                                                                                                              // 0.0
/*274 */                     if (pid_stat) {                                                                                                                                                                                                                             // 0.0
/*276 */                         char cpuperc[10];                                                                                                                                                                                                                       // 0.0
/*278 */                         char cpuused[64];                                                                                                                                                                                                                       // 0.0
/*282 */                         if (fscanf(pid_stat, "%9s %63s", cpuperc,                                                                                                                                                                                               // 0.0
/*284 */                                    cpuused) == 2) {                                                                                                                                                                                                             // 0.0
/*286 */                             avio_printf(pb, "Currently using %s%% of the cpu. Total time used %s.\n",                                                                                                                                                           // 0.0
/*288 */                                          cpuperc, cpuused);                                                                                                                                                                                                     // 0.0
/*290 */                         }                                                                                                                                                                                                                                       // 0.0
/*292 */                         fclose(pid_stat);                                                                                                                                                                                                                       // 0.0
/*294 */                     }                                                                                                                                                                                                                                           // 0.0
/*296 */                 }                                                                                                                                                                                                                                               // 0.0
/*298 */ #endif                                                                                                                                                                                                                                                          // 0.0
/*302 */                 avio_printf(pb, "<p>");                                                                                                                                                                                                                         // 0.0
/*304 */             }                                                                                                                                                                                                                                                   // 0.0
/*306 */             avio_printf(pb, "<table cellspacing=0 cellpadding=4><tr><th>Stream<th>type<th>kbits/s<th align=left>codec<th align=left>Parameters\n");                                                                                                             // 0.0
/*310 */             for (i = 0; i < stream->nb_streams; i++) {                                                                                                                                                                                                          // 0.0
/*312 */                 AVStream *st = stream->streams[i];                                                                                                                                                                                                              // 0.0
/*314 */                 AVCodec *codec = avcodec_find_encoder(st->codec->codec_id);                                                                                                                                                                                     // 0.0
/*316 */                 const char *type = "unknown";                                                                                                                                                                                                                   // 0.0
/*318 */                 char parameters[64];                                                                                                                                                                                                                            // 0.0
/*322 */                 parameters[0] = 0;                                                                                                                                                                                                                              // 0.0
/*326 */                 switch(st->codec->codec_type) {                                                                                                                                                                                                                 // 0.0
/*328 */                 case AVMEDIA_TYPE_AUDIO:                                                                                                                                                                                                                        // 0.0
/*330 */                     type = "audio";                                                                                                                                                                                                                             // 0.0
/*332 */                     snprintf(parameters, sizeof(parameters), "%d channel(s), %d Hz", st->codec->channels, st->codec->sample_rate);                                                                                                                              // 0.0
/*334 */                     break;                                                                                                                                                                                                                                      // 0.0
/*336 */                 case AVMEDIA_TYPE_VIDEO:                                                                                                                                                                                                                        // 0.0
/*338 */                     type = "video";                                                                                                                                                                                                                             // 0.0
/*340 */                     snprintf(parameters, sizeof(parameters), "%dx%d, q=%d-%d, fps=%d", st->codec->width, st->codec->height,                                                                                                                                     // 0.0
/*342 */                                 st->codec->qmin, st->codec->qmax, st->codec->time_base.den / st->codec->time_base.num);                                                                                                                                         // 0.0
/*344 */                     break;                                                                                                                                                                                                                                      // 0.0
/*346 */                 default:                                                                                                                                                                                                                                        // 0.0
/*348 */                     abort();                                                                                                                                                                                                                                    // 0.0
/*350 */                 }                                                                                                                                                                                                                                               // 0.0
/*352 */                 avio_printf(pb, "<tr><td align=right>%d<td>%s<td align=right>%d<td>%s<td>%s\n",                                                                                                                                                                 // 0.0
/*354 */                         i, type, st->codec->bit_rate/1000, codec ? codec->name : "", parameters);                                                                                                                                                               // 0.0
/*356 */             }                                                                                                                                                                                                                                                   // 0.0
/*358 */             avio_printf(pb, "</table>\n");                                                                                                                                                                                                                      // 0.0
/*362 */         }                                                                                                                                                                                                                                                       // 0.0
/*364 */         stream = stream->next;                                                                                                                                                                                                                                  // 0.0
/*366 */     }                                                                                                                                                                                                                                                           // 0.0
/*370 */     /* connection status */                                                                                                                                                                                                                                     // 0.0
/*372 */     avio_printf(pb, "<h2>Connection Status</h2>\n");                                                                                                                                                                                                            // 0.0
/*376 */     avio_printf(pb, "Number of connections: %d / %d<br>\n",                                                                                                                                                                                                     // 0.0
/*378 */                  nb_connections, nb_max_connections);                                                                                                                                                                                                           // 0.0
/*382 */     avio_printf(pb, "Bandwidth in use: %"PRIu64"k / %"PRIu64"k<br>\n",                                                                                                                                                                                          // 0.0
/*384 */                  current_bandwidth, max_bandwidth);                                                                                                                                                                                                             // 0.0
/*388 */     avio_printf(pb, "<table>\n");                                                                                                                                                                                                                               // 0.0
/*390 */     avio_printf(pb, "<tr><th>#<th>File<th>IP<th>Proto<th>State<th>Target bits/sec<th>Actual bits/sec<th>Bytes transferred\n");                                                                                                                                  // 0.0
/*392 */     c1 = first_http_ctx;                                                                                                                                                                                                                                        // 0.0
/*394 */     i = 0;                                                                                                                                                                                                                                                      // 0.0
/*396 */     while (c1 != NULL) {                                                                                                                                                                                                                                        // 0.0
/*398 */         int bitrate;                                                                                                                                                                                                                                            // 0.0
/*400 */         int j;                                                                                                                                                                                                                                                  // 0.0
/*404 */         bitrate = 0;                                                                                                                                                                                                                                            // 0.0
/*406 */         if (c1->stream) {                                                                                                                                                                                                                                       // 0.0
/*408 */             for (j = 0; j < c1->stream->nb_streams; j++) {                                                                                                                                                                                                      // 0.0
/*410 */                 if (!c1->stream->feed)                                                                                                                                                                                                                          // 0.0
/*412 */                     bitrate += c1->stream->streams[j]->codec->bit_rate;                                                                                                                                                                                         // 0.0
/*414 */                 else if (c1->feed_streams[j] >= 0)                                                                                                                                                                                                              // 0.0
/*416 */                     bitrate += c1->stream->feed->streams[c1->feed_streams[j]]->codec->bit_rate;                                                                                                                                                                 // 0.0
/*418 */             }                                                                                                                                                                                                                                                   // 0.0
/*420 */         }                                                                                                                                                                                                                                                       // 0.0
/*424 */         i++;                                                                                                                                                                                                                                                    // 0.0
/*426 */         p = inet_ntoa(c1->from_addr.sin_addr);                                                                                                                                                                                                                  // 0.0
/*428 */         avio_printf(pb, "<tr><td><b>%d</b><td>%s%s<td>%s<td>%s<td>%s<td align=right>",                                                                                                                                                                          // 0.0
/*430 */                     i,                                                                                                                                                                                                                                          // 0.0
/*432 */                     c1->stream ? c1->stream->filename : "",                                                                                                                                                                                                     // 0.0
/*434 */                     c1->state == HTTPSTATE_RECEIVE_DATA ? "(input)" : "",                                                                                                                                                                                       // 0.0
/*436 */                     p,                                                                                                                                                                                                                                          // 0.0
/*438 */                     c1->protocol,                                                                                                                                                                                                                               // 0.0
/*440 */                     http_state[c1->state]);                                                                                                                                                                                                                     // 0.0
/*442 */         fmt_bytecount(pb, bitrate);                                                                                                                                                                                                                             // 0.0
/*444 */         avio_printf(pb, "<td align=right>");                                                                                                                                                                                                                    // 0.0
/*446 */         fmt_bytecount(pb, compute_datarate(&c1->datarate, c1->data_count) * 8);                                                                                                                                                                                 // 0.0
/*448 */         avio_printf(pb, "<td align=right>");                                                                                                                                                                                                                    // 0.0
/*450 */         fmt_bytecount(pb, c1->data_count);                                                                                                                                                                                                                      // 0.0
/*452 */         avio_printf(pb, "\n");                                                                                                                                                                                                                                  // 0.0
/*454 */         c1 = c1->next;                                                                                                                                                                                                                                          // 0.0
/*456 */     }                                                                                                                                                                                                                                                           // 0.0
/*458 */     avio_printf(pb, "</table>\n");                                                                                                                                                                                                                              // 0.0
/*462 */     /* date */                                                                                                                                                                                                                                                  // 0.0
/*464 */     ti = time(NULL);                                                                                                                                                                                                                                            // 0.0
/*466 */     p = ctime(&ti);                                                                                                                                                                                                                                             // 0.0
/*468 */     avio_printf(pb, "<hr size=1 noshade>Generated at %s", p);                                                                                                                                                                                                   // 0.0
/*470 */     avio_printf(pb, "</body>\n</html>\n");                                                                                                                                                                                                                      // 0.0
/*474 */     len = avio_close_dyn_buf(pb, &c->pb_buffer);                                                                                                                                                                                                                // 0.0
/*476 */     c->buffer_ptr = c->pb_buffer;                                                                                                                                                                                                                               // 0.0
/*478 */     c->buffer_end = c->pb_buffer + len;                                                                                                                                                                                                                         // 0.0
/*480 */ }                                                                                                                                                                                                                                                               // 0.0
